mapped_icd_codes = {
    "999": "Unknown",
    "99": "Unknown",
    "3": "Unknown",
    "5": "Unknown",
    "Z032": "Observasjon ved mistanke om psykisk lidelse eller atferdsforstyrrelse",
    "F941": "Reaktiv tilknytningsforstyrrelse i barndommen",
    "4.1": "Unknown",
    "F901": "Hyperkinetisk atferdsforstyrrelse",
    "2": "Unknown",
    "1.0": "Unknown",
    "4": "Unknown",
    "1": "Unknown",
    "G40": "Epilepsi",
    "F845": "Aspergers syndrom",
    "F948": "Annen spesifisert forstyrrelse av sosial fungering i barndommen",
    "F908": "Annen spesifisert hyperkinetisk forstyrrelse",
    "5.1": "Unknown",
    "F341": "Dystymi",
    "F900": "Forstyrrelse av aktivitet eller oppmerksomhet",
    "000": "Unknown",
    "2.0": "Unknown",
    "F801": "Ekspressiv språkforstyrrelse",
    "F952": "Kombinerte vokale og multiple motoriske «tics» Tourettes syndrom",
    "9": "Unknown",
    "F813": "Blandet utviklingsforstyrrelse i skoleferdighet",
    "8.0": "Unknown",
    "F198": "Annen spesifisert psykisk lidelse eller atferdsforstyrrelse som skyldes bruk av andre eller flere psykoaktive stoffer",
    "00": "Unknown",
    "F431": "Posttraumatisk stresslidelse [PTSD]",
    "F432": "Tilpasningsforstyrrelse",
    "F920": "Depressiv atferdsforstyrrelse",
    "F719": "Moderat psykisk utviklingshemming uten beskrivelse av atferdsproblem",
    "F939": "Uspesifisert følelsesmessig forstyrrelse i barndommen",
    "M511": "Lidelse i lumbalskive og andre mellomvirvelskiver, med radikulopati",
    "2.2": "Unknown",
    "2.1": "Unknown",
    "5.3": "Unknown",
    "F913": "Opposisjonell atferdsforstyrrelse",
    "F938": "Annen spesifisert følelsesmessig forstyrrelse i barndommen",
    "45": "Unknown",
    "6.3": "Unknown",
    "K590": "Forstoppelse",
    "R32": "Uspesifisert inkontinens",
    "G409": "Uspesifisert epilepsi",
    "F709": "Lett psykisk utviklingshemming uten beskrivelse av atferdsproblem",
    "2000": "Unknown",
    "3000": "Unknown",
    "4000": "Unknown",
    "F321": "Moderat depressiv episode",
    "H520": "Langsynthet",
    "F909": "Uspesifisert hyperkinetisk forstyrrelse",
    "65": "Unknown",
    "F190": "Akutt intoksikasjon med andre eller flere psykoaktive stoffer",
    "F701": "Lett psykisk utviklingshemming med betydelig atferdsproblem",
    "50": "Unknown",
    "F191": "Skadelig bruk av andre eller flere psykoaktive stoffer",
    "F422": "Tvangslidelse med blandede tvangstanker og tvangshandlinger [tvangsritualer]",
    "F322": "Alvorlig depressiv episode uten psykotisk symptom",
    "32": "Unknown",
    "5.0": "Unknown",
    "F332": "Tilbakevendende depressiv lidelse med aktuell alvorlig episode uten psykotisk symptom",
    "X6nx": "Villet egenskade på ukjent sted",
    "1000": "Unknown",
    "F410": "Panikklidelse [episodisk paroksysmal angst]",
    "2999": "Unknown",
    "3999": "Unknown",
    "4999": "Unknown",
    "F331": "Tilbakevendende depressiv lidelse med aktuell moderat episode",
    "60": "Unknown",
    "F710": "Moderat psykisk utviklingshemming med ingen eller minimalt atferdsproblem",
    "1999": "Unknown",
    "1.1": "Unknown",
    "S223": "Brudd i ribben",
    "80": "Unknown",
    "58": "Unknown",
    "F411": "Generalisert angstlidelse",
    "5999": "Unknown",
    "6999": "Unknown",
    "66": "Unknown",
    "6.1": "Unknown",
    "5000": "Unknown",
    "52": "Unknown",
    "F951": "Kroniske motoriske eller vokale «tics»",
    "F330": "Tilbakevendende depressiv lidelse med aktuell mild episode",
    "F459": "Uspesifisert somatoform lidelse",
    "F329": "Uspesifisert depressiv episode",
    "P015": "Foster eller nyfødt påvirket av flersvangerskap",
    "F849": "Uspesifisert gjennomgripende utviklingsforstyrrelse",
    "64": "Unknown",
    "F503": "Atypisk bulimia nervosa",
    "6000": "Unknown",
    "P073": "Annet for tidlig født barn",
    "J392": "Annen sykdom i svelg",
    "37": "Unknown",
    "G404": "Annen generalisert epilepsi eller epileptisk syndrom",
    "6.4": "Unknown",
    "F401": "Sosial fobi",
    "48": "Unknown",
    "4.2": "Unknown",
    "55": "Unknown",
    "69": "Unknown",
    "F82": "Spesifikk utviklingsforstyrrelse i motorisk ferdighet",
    "F700": "Lett psykisk utviklingshemming med ingen eller minimalt atferdsproblem",
    "78": "Unknown",
    "F810": "Spesifikk leseforstyrrelse",
    "F421": "Tvangslidelse med hovedsakelig tvangshandlinger [tvangsritualer]",
    "F910": "Atferdsforstyrrelse begrenset til familien",
    "F3200": "Mild depressiv episode uten somatisk syndrom",
    "57": "Unknown",
    "F811": "Spesifikk staveforstyrrelse",
    "R51": "Hodepine",
    "75": "Unknown",
    "F929": "Uspesifisert blandet atferdsforstyrrelse eller følelsesmessig forstyrrelse",
    "F608": "Annen spesifikk personlighetsforstyrrelse",
    "P0711": "Annen lav fødselsvekt, 1000-1499g",
    "68": "Unknown",
    "F3310": "Tilbakevendende depressiv lidelse med aktuell moderat episode uten somatisk syndrom",
    "F83": "Blandet utviklingsforstyrrelse i spesifikke ferdigheter",
    "F606": "Engstelig [unnvikende] personlighetsforstyrrelse",
    "F942": "Udiskriminerende tilknytningsforstyrrelse i barndommen",
    "71": "Unknown",
    "F444": "Dissosiativ motorisk forstyrrelse",
    "S830": "Dislokasjon av kneskål",
    "J459": "Uspesifisert astma",
    "53": "Unknown",
    "F420": "Tvangslidelse med hovedsakelig tvangstanker eller tvangsgrubling",
    "81": "Unknown",
    "F808": "Annen spesifisert utviklingsforstyrrelse av tale eller språk",
    "Z712": "Kontakt for å få forklaring på undersøkelsesresultat",
    "47": "Unknown",
    "49": "Unknown",
    "G801": "Spastisk diplegisk cerebral parese",
    "9.0": "Unknown",
    "F912": "Sosialisert atferdsforstyrrelse",
    "51": "Unknown",
    "43": "Unknown",
    "F980": "Ikke-organisk enurese",
    "1.4": "Unknown",
    "F438": "Annen spesifisert reaksjon på alvorlig belastning",
    "40": "Unknown",
    "F509": "Uspesifisert spiseforstyrrelse",
    "1.8": "Unknown",
    "F320": "Mild depressiv episode",
    "62": "Unknown",
    "8.8": "Unknown",
    "72": "Unknown",
    "D821": "Di Georges syndrom",
    "F819": "Uspesifisert utviklingsforstyrrelse i skoleferdighet",
    "70": "Unknown",
    "E669": "Uspesifisert fedme",
    "46": "Unknown",
    "F928": "Annen spesifisert blandet atferdsforstyrrelse eller følelsesmessig forstyrrelse",
    "Z133": "Kontakt med helsetjenesten for populasjonsbasert screeningundersøkelse med henblikk på psykisk lidelse eller atferdsforstyrrelse",
    "38": "Unknown",
    "F911": "Usosialisert atferdsforstyrrelse",
    "G933": "Postviralt utmattelsessyndrom",
    "54": "Unknown",
    "F4322": "Blandet angstreaksjon og depressiv reaksjon",
    "F500": "Anorexia nervosa",
    "6.5": "Unknown",
    "8.2": "Unknown",
    "F454": "Vedvarende somatoform smertelidelse",
    "F4325": "Tilpasningsforstyrrelse med blandet forstyrrelse av følelser og atferd",
    "6.2": "Unknown",
    "F708": "Lett psykisk utviklingshemming med annen angivelse av atferdsproblem",
    "61": "Unknown",
    "56": "Unknown",
    "1.3": "Unknown",
    "44": "Unknown",
    "nan": "Unknown",
    "F989": "Uspesifisert atferdforstyrrelse eller følelsesmessig forstyrrelse som vanligvis oppstår i barne- eller ungdomsalder",
    "D509": "Uspesifisert jernmangelanemi",
    "F1024": "Alkoholavhengighetssyndrom, for tiden bruker (aktiv avhengighet)",
    "42": "Unknown",
    "G470": "Innsovningsforstyrrelse eller søvnforstyrrelse",
    "76": "Unknown",
    "T001": "Overflateskader som omfatter brystkasse med buk, nedre del av rygg eller bekken",
    "F439": "Uspesifisert reaksjon på alvorlig belastning",
    "F930": "Separasjonsangst i barndommen",
    "67": "Unknown",
    "63": "Unknown",
    "F4321": "Vedvarende depressiv reaksjon",
    "X6n0": "Villet egenskade i bolig eller boligområde",
    "F419": "Uspesifisert angstlidelse",
    "F29": "Uspesifisert ikke-organisk psykose",
    "F1221": "Cannabinoidavhengighetssyndrom, for tiden abstinent, men i beskyttede omgivelser",
    "H901": "Unilateralt mekanisk hørselstap uten nedsatt hørsel på motsatt side",
    "R620": "Forsinket oppnåelse av utviklingsmilepæl",
    "5.2": "Unknown",
    "O421": "For tidlig vannavgang med start av fødsel etter 24 timer",
    "74": "Unknown",
    "F323": "Alvorlig depressiv episode med psykotisk symptom",
    "36": "Unknown",
    "33": "Unknown",
    "R458": "Annet spesifisert symptom eller tegn med tilknytning til emosjonell tilstand",
    "F412": "Blandet angstlidelse og depressiv lidelse",
    "R468": "Annet spesifisert symptom eller tegn med tilknytning til utseende eller atferd",
    "S607": "Flere overflateskader på håndledd eller hånd",
    "F418": "Annen spesifisert angstlidelse",
    "E890": "Hypotyreose etter kirurgiske eller medisinske prosedyrer",
    "F802": "Impressiv språkforstyrrelse",
    "F21": "Schizotyp lidelse",
    "6.0": "Unknown",
    "G439": "Uspesifisert migrene",
    "E660": "Fedme som skyldes høyt kaloriinntak",
    "R448": "Annet eller uspesifisert symptom eller tegn med tilknytning til generelle sensasjoner eller persepsjoner",
    "F408": "Annen spesifisert fobisk angstlidelse",
    "F510": "Ikke-organisk insomni",
    "G472": "Forstyrrelse i søvn-våkenhetsrytmen",
    "F950": "Forbigående «tics»",
    "F661": "Jeg-fremmed seksuell legning",
    "86": "Unknown",
    "F809": "Uspesifisert utviklingsforstyrrelse av tale eller språk",
    "4.0": "Unknown",
    "R63": "Symptomer og tegn med tilknytning til mat- og væskeinntak",
    "F199": "Uspesifisert psykisk lidelse eller atferdsforstyrrelse som skyldes bruk av andre eller flere psykoaktive stoffer",
    "41": "Unknown",
    "F200": "Paranoid schizofreni",
    "F818": "Annen spesifisert utviklingsforstyrrelse i skoleferdighet",
    "F840": "Barneautisme",
    "P0712": "Annen lav fødselsvekt, 1500-1999g",
    "F448": "Annen spesifisert dissosiativ lidelse [konversjonslidelse]",
    "S617": "Flere åpne sår på håndledd eller hånd",
    "F988": "Annen spesifisert atferdsforstyrrelse eller følelsesmessig forstyrrelse som vanligvis oppstår i barne- eller ungdomsalder",
    "G430": "Migrene uten aura",
    "Z5080": "Kontakt med helsetjenesten for kompleks rehabilitering",
    "E109": "Diabetes mellitus type 1 uten komplikasjon",
    "Q850": "Nevrofibromatose",
    "7.1": "Unknown",
    "G442": "Tensjonshodepine",
    "E104": "Diabetes mellitus type 1 med nevrologisk komplikasjon",
    "9.8": "Unknown",
    "F480": "Nevrasteni",
    "F4323": "Tilpasningsforstyrrelse med dominerende forstyrrelse av annet følelser",
    "F449": "Uspesifisert dissosiativ lidelse [konversjonslidelse]",
    "F4000": "Agorafobi uten panikklidelse",
    "F446": "Dissosiativ følelsesløshet eller sanseutfall",
    "F4488": "Annen spesifisert dissosiativ lidelse [konversjonslidelse]",
    "85": "Unknown",
    "F940": "Elektiv mutisme",
    "C910": "Akutt lymfoblastisk leukemi",
    "R15": "Ufrivillig avføring",
    "73": "Unknown",
    "59": "Unknown",
    "8.1": "Unknown",
    "35": "Unknown",
    "F102": "Alkoholavhengighetssyndrom",
    "F340": "Cyklotymi",
    "F4001": "Agorafobi med panikklidelse",
    "Q740": "Annen medfødt misdannelse i overekstremitet eller skulderbue",
    "F402": "Spesifikk (isolert) fobi",
    "T4n": "Forgiftning med terapeutisk legemiddel eller biologisk substans",
    "F28": "Annen ikke-organisk psykose",
    "T002": "Overflateskader som omfatter flere regioner av en eller begge overekstremiteter",
    "F400": "Agorafobi",
    "E559": "Uspesifisert D-vitaminmangel",
    "1.2": "Unknown",
    "R463": "Overaktivitet",
    "Q120": "Medfødt grå stær",
    "R440": "Hørselshallusinasjoner",
    "G802": "Spastisk hemiplegisk cerebral parese",
    "82": "Unknown",
    "H201": "Kronisk iridosyklitt",
    "26": "Unknown",
    "F230": "Akutt polymorf psykose (non-schizofreniform)",
    "X6n5": "Villet egenskade i somatisk eller psykiatrisk sykehus eller helseinstitusjon",
    "F430": "Akutt belastningslidelse",
    "9.1": "Unknown",
    "R638": "Annet spesifisert symptom eller tegn med tilknytning til mat- eller væskeinntak",
    "31": "Unknown",
    "R53": "Uvelhet eller tretthet",
    "F6031": "Emosjonelt ustabil personlighetsforstyrrelse av borderline type",
    "F228": "Annen spesifisert paranoid psykose",
    "H903": "Bilateralt nevrogent hørselstap",
    "Z358": "Kontroll av annet spesifisert høyrisikosvangerskap",
    "E108": "Diabetes mellitus type 1 med uspesifisert komplikasjon",
    "E661": "Legemiddelutløst fedme",
    "F319": "Uspesifisert bipolar affektiv lidelse",
    "Q250": "Åpen ductus arteriosus",
    "88": "Unknown",
    "F518": "Annen spesifisert ikke-organisk søvnforstyrrelse",
    "R418": "Annet eller uspesifisert symptom eller tegn med tilknytning til kognitiv funksjon eller bevissthet",
    "T751": "Drukning eller nestendrukning",
    "X6n2": "Villet egenskade ved annen ulykke på gate eller vei",
    "Y912": "Betydelig alkoholpåvirkning",
    "G719": "Uspesifisert primær muskelsykdom",
    "F601": "Schizoid personlighetsforstyrrelse",
    "6": "Unknown",
    "S417": "Flere åpne sår på skulder eller overarm",
    "S817": "Flere åpne sår på legg",
    "R452": "Ulykkelighet",
    "R000": "Uspesifisert takykardi",
    "R466": "Overdreven engstelse eller bekymring ved stressituasjoner",
    "Z710": "Kontakt med helsetjenesten på vegne av annen person",
    "R450": "Nervøsitet",
    "34": "Unknown",
    "F981": "Ikke-organisk enkoprese",
    "22": "Unknown",
    "F649": "Unknown",
    "R457": "Uspesifisert tilstand av emosjonelt sjokk eller stress",
    "F982": "Spiseforstyrrelse i barndommen",
    "R454": "Irritabilitet eller sinne",
    "R464": "Langsom eller dårlig reaksjonsevne",
    "F452": "Hypokondrisk lidelse",
    "R451": "Rastløshet eller agitasjon",
    "F3201": "Mild depressiv episode med somatisk syndrom",
    "F4320": "Kortvarig depressiv reaksjon",
    "F3211": "Moderat depressiv episode med somatisk syndrom",
    "Z708": "Kontakt med helsetjenesten for annen spesifisert rådgivning i seksuelt spørsmål",
    "F501": "Atypisk anorexia nervosa",
    "F54": "Psykisk eller atferdsmessig forstyrrelse forbundet med forstyrrelse eller lidelse klassifisert annet sted",
    "E46": "Uspesifisert protein-/energiunderernæring",
    "E100": "Diabetes mellitus type 1 med koma",
    "90": "Unknown",
    "F209": "Uspesifisert schizofreni",
    "R42": "Svimmelhet",
    "G431": "Migrene med aura",
    "M828": "Osteoporose ved annen sykdom klassifisert annet sted",
    "F642": "Unknown",
    "C719": "Ondartet svulst med uspesifisert lokalisasjon i hjerne",
    "F334": "Tilbakevendende depressiv lidelse i remisjon",
    "F949": "Uspesifisert forstyrrelse av sosial fungering i barndommen",
    "F151": "Skadelig bruk av annen stimulant, inklusive kaffein",
    "Z004": "Kontakt med helsetjenesten for generell psykiatrisk undersøkelse ikke klassifisert annet sted",
    "F3210": "Moderat depressiv episode uten somatisk syndrom",
    "Z134": "Kontakt med helsetjenesten for populasjonsbasert screeningundersøkelse med henblikk på enkelte utviklingsavvik i barneårene",
    "F502": "Bulimia nervosa",
    "6.8": "Unknown",
    "7.8": "Unknown",
    "Q203": "Transposisjon av de store arterier",
    "F458": "Annen spesifisert somatoform lidelse",
    "15": "Unknown",
    "F429": "Uspesifisert obsessiv-kompulsiv lidelse",
    "30": "Unknown",
    "M858": "Annen spesifisert forstyrrelse i bentetthet og benstruktur",
    "F4328": "Tilpasningsforstyrrelse med annet spesifisert dominerende symptom",
    "E876": "Hypokalemi",
    "P0702": "Ekstremt lav fødselsvekt, 500-749g",
    "F4324": "Tilpasningsforstyrrelse med dominerende atferdsforstyrrelse",
    "T742": "Seksuell mishandling",
    "89": "Unknown",
    "Z876": "Opplysning om visse tilstander som oppstår i perinatalperioden i egen sykehistorie",
    "J304": "Uspesifisert allergisk rhinitt",
    "F959": "Uspesifisert «tics»",
    "4.3": "Unknown",
    "R441": "Synshallusinasjoner",
    "4.8": "Unknown",
    "2.8": "Unknown",
    "F09": "Uspesifisert organisk eller symptomatisk psykisk lidelse",
    "R11": "Kvalme eller oppkast",
    "F2000": "Kronisk paranoid schizofreni",
    "F233": "Akutt paranoid psykose",
    "S507": "Flere overflateskader på underarm",
    "F201": "Hebefren schizofreni",
    "F489": "Uspesifisert nevrotisk lidelse",
    "X6n9": "Villet egenskade på annet sted",
    "92": "Unknown",
    "F512": "Ikke-organisk forstyrrelse av søvn-våkenhetsrytmen",
    "9.2": "Unknown",
    "77": "Unknown",
    "87": "Unknown",
    "84": "Unknown",
    "79": "Unknown",
    "7.0": "Unknown",
    "F99": "Uspesifisert psykisk forstyrrelse eller lidelse",
    "F328": "Annen spesifisert depressiv episode",
    "83": "Unknown",
    "E106": "Diabetes mellitus type 1 med annen spesifisert komplikasjon",
    "F932": "Sosial angstlidelse i barndommen",
    "J46": "Akutt alvorlig astma",
    "F640": "Unknown",
    "F121": "Skadelig bruk av cannabinoid",
    "H509": "Uspesifisert skjeling",
    "G80": "Cerebral parese",
    "F068": "Annen spesifisert organisk psykisk lidelse",
    "F812": "Spesifikk forstyrrelse i regneferdighet",
    "24": "Unknown",
    "F380": "Annen enkeltstående affektiv lidelse",
    "F122": "Cannabinoidavhengighetssyndrom",
    "F798": "Uspesifisert psykisk utviklingshemming med annet spesifisert atferdsproblem",
    "N300": "Akutt cystitt",
    "F1521": "Avhengighetssyndrom som skyldes bruk av annen stimulant, inklusive kaffein, for tiden abstinent, men i beskyttede omgivelser",
    "F203": "Udifferensiert schizofreni",
    "F1621": "Hallusinogenavhengighetssyndrom, for tiden abstinent, men i beskyttede omgivelser",
    "S517": "Flere åpne sår på underarm",
    "R478": "Annen eller uspesifisert taleforstyrrelse",
    "F252": "Schizoaffektiv lidelse av blandet manisk-depressiv type",
    "J301": "Allergisk rhinitt som skyldes pollen",
    "J029": "Uspesifisert akutt faryngitt",
    "E039": "Uspesifisert hypotyreose",
    "M245": "Kontraktur i ledd",
    "M791": "Myalgi",
    "J960": "Akutt respirasjonssvikt",
    "T71": "Asfyksi",
    "G932": "Godartet intrakraniell hypertensjon",
    "Q282": "Arteriovenøs misdannelse i cerebralt kar",
    "Q969": "Uspesifisert Turners syndrom",
    "M084": "Pauciartikulær juvenil artritt",
    "Z038": "Observasjon ved mistanke om annen spesifisert sykdom eller tilstand",
    "Q049": "Uspesifisert medfødt misdannelse i hjernen",
    "Q625": "Duplikasjon av urinleder",
    "P211": "Lett eller moderat fødselsasfyksi",
    "P0713": "Annen lav fødselsvekt, 2000-2499g",
    "K900": "Cøliaki",
    "D353": "Godartet svulst i ductus craniopharyngealis",
    "H540": "Blindhet i begge øyne",
    "D693": "Immunologisk trombocytopeni",
    "E038": "Annen spesifisert hypotyreose",
    "R633": "Vanskeligheter med inntak eller tilførsel av mat",
    "M925": "Juvenil osteokondrose i skinneben eller leggben",
    "E893": "Hypopituitarisme etter kirurgiske eller medisinske prosedyrer",
    "R104": "Annen eller uspesifisert smerte i buk eller bekken",
    "F313": "Bipolar affektiv lidelse med aktuell episode med mild eller moderat depresjon",
    "M911": "Juvenil osteokondrose i lårbenshode",
    "T784": "Uspesifisert allergi",
    "J450": "Hovedsakelig allergisk astma",
    "1.5": "Unknown",
    "F413": "Annen blandet angstlidelse",
    "G408": "Annen spesifisert epilepsi",
    "F630": "Patologisk spillelidenskap",
    "F919": "Uspesifisert atferdsforstyrrelse",
    "11": "Unknown",
    "F409": "Uspesifisert fobisk angstlidelse",
    "R568": "Annen eller uspesifisert krampe",
    "D181": "Lymfangiom med enhver lokalisasjon",
    "G474": "Narkolepsi eller katapleksi",
    "25": "Unknown",
    "X6n": "Villet egenskade",
    "7": "Unknown",
    "Q230": "Medfødt valvulær aortastenose",
    "M890": "Regionalt smertesyndrom",
    "D593": "Hemolytisk-uremisk sykdom",
    "A09": "Annen gastroenteritt og kolitt av infeksiøs og uspesifisert årsak",
    "Q422": "Medfødt mangel på, atresi av eller stenose av endetarmsåpning, med fistel",
    "Q420": "Medfødt mangel på, atresi av eller stenose av endetarm eller analkanal, med fistel",
    "D761": "Hemofagocyttær lymfohistiocytose",
    "K580": "Unknown",
    "S024": "Brudd i kinnben og overkjeveben",
    "Q226": "Hypoplastisk høyre hjerte-syndrom",
    "P072": "Ekstrem immaturitet",
    "P210": "Alvorlig fødselsasfyksi",
    "E343": "Kortvoksthet ikke klassifisert annet sted",
    "Z033": "Observasjon ved mistanke om forstyrrelse i nervesystemet",
    "Q046": "Medfødt hjernecyste",
    "C64": "Ondartet svulst i nyre unntatt nyrebekken",
    "T888": "Annen spesifisert komplikasjon til kirurgisk eller medisinsk behandling, ikke klassifisert annet sted",
    "S827": "Flere brudd i legg",
    "M765": "Patellar senetendinitt",
    "Z643": "Oppsøking eller akseptering av atferdsmessig eller psykologisk påvirkning som er kjent for å være risikofylt eller skadelig",
    "Q201": "Dobbelt utløp fra høyre hjertekammer",
    "S025": "Brudd i tann",
    "S360": "Skade på milt",
    "S361": "Skade på lever eller galleblære",
    "S0630": "Fokal hjerneskade uten åpen intrakraniell skade",
    "S065": "Traumatisk eller uspesifisert subduralblødning",
    "S021": "Brudd på skallebasis",
    "F447": "Blandet dissosiativ lidelse [konversjonslidelse]",
    "R29": "Andre symptomer og tegn med tilknytning til nervesystemet og muskel-skjelettsystemet",
    "R635": "Unormal vektøkning",
    "J324": "Kronisk pansinusitt",
    "R26": "Unormal gange og bevegelighet",
    "R412": "Retrograd amnesi",
    "R470": "Dysfasi eller afasi",
    "R462": "Merkelig eller uforklarlig opptreden",
    "G000": "Hemofilusmeningitt",
    "J690": "Pneumoni forårsaket av mat eller oppkast",
    "G910": "Kommuniserende hydrocephalus",
    "Q070": "Arnold-Chiaris syndrom",
    "C811": "(Klassisk) Hodgkins sykdom av type nodulær sklerose",
    "S683": "Fullstendig eller delvis traumatisk amputasjon av finger eller fingre kombinert med annen del av håndledd eller hånd",
    "C621": "Ondartet svulst i descendert testikkel",
    "I618": "Annen spesifisert hjerneblødning",
    "S0660": "Traumatisk subaraknoidalblødning uten åpen intrakraniell skade",
    "F508": "Annen spesifisert spiseforstyrrelse",
    "S300": "Kontusjon av nedre del av rygg og bekken",
    "S7230": "Lukket brudd i lårbensskaft",
    "I279": "Uspesifisert pulmonal hjertesykdom",
    "Q218": "Annen spesifisert medfødt misdannelse i hjerteskillevegg",
    "E43": "Uspesifisert alvorlig protein-/energiunderernæring",
    "E833": "Forstyrrelse i fosformetabolismen eller fosfataser",
    "E233": "Hypothalamisk dysfunksjon ikke klassifisert annet sted",
    "Z701": "Kontakt med helsetjenesten for rådgivning i forbindelse med pasientens seksuelle atferd eller orientering",
    "8": "Unknown",
    "Q431": "Hirschsprungs sykdom",
    "S524": "Brudd i både ulna- og radiusskaft",
    "T814": "Infeksjon etter kirurgiske eller medisinske prosedyrer ikke klassifisert annet sted",
    "F958": "Annet spesifisert syndrom med «tics»",
    "R630": "Anoreksi",
    "G402": "Lokalisasjonsrelatert symptomatisk epilepsi eller epileptisk syndrom med komplekse partielle anfall",
    "I693": "Følgetilstand etter hjerneinfarkt",
    "F799": "Uspesifisert psykisk utviklingshemming uten beskrivelse av atferdsproblem",
    "T280": "Brannskade av munn eller svelg",
    "Q790": "Medfødt mellomgulvsbrokk",
    "E668": "Annen spesifisert fedme",
    "M8906": "Regionalt smertesyndrom i legg",
    "Z041": "Undersøkelse eller observasjon etter transportulykke",
    "E86": "Dehydrering",
    "T510": "Toksisk virkning av etanol",
    "F100": "Akutt alkoholintoksikasjon",
    "S822": "Brudd i skinnebensskaft",
    "M4115": "Juvenil idiopatisk skoliose i torakolumbalregionen",
    "Q900": "Trisomi 21, meiotisk nondisjunksjon",
    "G403": "Generalisert idiopatisk epilepsi eller epileptisk syndrom",
    "I951": "Ortostatisk hypotensjon",
    "95": "Unknown",
    "K509": "Crohns sykdom med uspesifisert lokalisasjon",
    "M357": "Hypermobilitetssyndrom",
    "F0594": "Unknown",
    "N394": "Annen spesifisert urininkontinens",
    "Q963": "Mosaikk, 45,X/46,XX eller XY",
    "Z724": "Problem i forbindelse med uhensiktsmessig kosthold eller spisevaner",
    "I500": "Kongestiv hjertesvikt",
    "Q793": "Gastroschisis",
    "T810": "Blødning eller hematom som komplikasjon til kirurgiske eller medisinske prosedyrer, ikke klassifisert annet sted",
    "M082": "Juvenil artritt med systemisk opprinnelse",
    "P0703": "Ekstremt lav fødselsvekt, 750-999g",
    "Z509": "Kontakt med helsetjenesten for behandling som omfatter bruk av uspesifisert rehabiliteringstiltak",
    "E101": "Diabetes mellitus type 1 med ketoacidose",
    "C091": "Ondartet svulst i ganebue",
    "M080": "Juvenil revmatoid artritt",
    "E760": "Mukopolysakkaridose, type I",
    "G822": "Uspesifisert paraplegi",
    "R55": "Synkope eller kollaps",
    "R064": "Hyperventilering",
    "G441": "Vaskulær hodepine ikke klassifisert annet sted",
    "R628": "Annen spesifisert uteblivelse av forventet normal fysiologisk utvikling",
    "Q627": "Medfødt vesikoureterorenal refluks",
    "N133": "Annen eller uspesifisert hydronefrose",
    "E063": "Autoimmun tyreoiditt",
    "C222": "Hepatoblastom",
    "Z944": "Status etter transplantert lever",
    "R298": "Annet eller uspesifisert symptom eller tegn med tilknytning til nervesystemet eller muskel-skjelettsystemet",
    "P612": "Prematuritetsanemi",
    "H351": "Retinopati hos prematur",
    "E840": "Cystisk fibrose med lungesymptom",
    "C859": "Uspesifisert non-Hodgkin lymfom",
    "O229": "Uspesifisert venøs komplikasjon under svangerskap",
    "0": "Unknown",
    "R634": "Unormalt vekttap",
    "Z044": "Undersøkelse eller observasjon etter påstått voldtekt",
    "H919": "Uspesifisert hørselstap",
    "Z048": "Undersøkelse eller observasjon av annen spesifisert årsak",
    "M083": "Juvenil seronegativ polyartritt",
    "R465": "Mistenksomhet eller påfallende unnvikenhet",
    "K510": "Ulcerøs pankolitt",
    "N47": "Overflødig forhud, fimose eller parafimose",
    "5.8": "Unknown",
    "Z615": "Problem i forbindelse med påstått seksuelt misbruk av barn utført av personer utenfor barnets primærkontakter",
    "R443": "Uspesifiserte hallusinasjoner",
    "F317": "Bipolar affektiv lidelse i remisjon",
    "B589": "Uspesifisert toksoplasmose",
    "Z915": "Opplysning om tidligere selvpåført skade",
    "F220": "Paranoid psykose (vrangforestillingslidelse)",
    "F232": "Akutt schizofrenilignende psykose",
    "F428": "Annen spesifisert obsessiv-kompulsiv lidelse",
    "21": "Unknown",
    "L709": "Uspesifisert akne",
    "28": "Unknown",
    "F2391": "Akutt forbigående uspesifisert psykose med akutt påkjenning",
    "I061": "Revmatisk aortainsuffisiens",
    "18": "Unknown",
    "F078": "Annen spesifisert organisk personlighets- eller atferdsforstyrrelse",
    "F2390": "Akutt forbigående uspesifisert psykose uten akutt påkjenning",
    "F302": "Mani med psykotisk symptom",
    "Z703": "Kontakt med helsetjenesten for rådgivning i forbindelse med bekymring på flere områder innen holdning til seksualitet eller seksuell atferd eller orientering",
    "E300": "Forsinket pubertet",
    "D70": "Agranulocytose eller nøytropeni",
    "S618": "Åpent sår på annen spesifisert del av håndledd eller hånd",
    "T006": "Overflateskader som omfatter flere regioner av overekstremiteter med underekstremiteter",
    "F101": "Skadelig bruk av alkohol",
    "F238": "Annen type akutt forbigående psykose",
    "R442": "Andre hallusinasjoner",
    "F519": "Uspesifisert ikke-organisk søvnlidelse",
    "G407": "Uspesifisert epilepsi med absenser uten tonisk-kloniske anfall",
    "S060": "Hjernerystelse",
    "F89": "Uspesifisert forstyrrelse av psykologisk utvikling",
    "F88": "Annen forstyrrelse av psykologisk utvikling",
    "E45": "Forsinket utvikling som følge av protein-/energiunderernæring",
    "F442": "Dissosiativ stupor",
    "Q100": "Medfødt ptosis",
    "T780": "Anafylaktisk sjokk som skyldes reaksjon på matvare",
    "F314": "Bipolar affektiv lidelse med aktuell episode med alvorlig depresjon uten psykotisk symptom",
    "Q860": "Føtalt alkoholsyndrom",
    "Q780": "Osteogenesis imperfecta",
    "Q189": "Uspesifisert medfødt misdannelse i ansikt eller hals",
    "H545": "Alvorlig svekket syn i ett øye",
    "K228": "Annen spesifisert sykdom i spiserør",
    "L209": "Uspesifisert atopisk dermatitt",
    "Q738": "Annen reduksjonsdefekt i uspesifisert ekstremitet",
    "M410": "Infantil idiopatisk skoliose",
    "H902": "Uspesifisert mekanisk hørselstap",
    "29": "Unknown",
    "F639": "Uspesifisert vane- eller impulsforstyrrelse",
    "20": "Unknown",
    "M7911": "Myalgi i skulderregionen",
    "Q254": "Annen medfødt misdannelse av aorta",
    "Q858": "Annen spesifisert fakomatose, ikke klassifisert annet sted",
    "H405": "Glaukom etter annen øyelidelse",
    "Q825": "Medfødt ikke-neoplastisk nevus",
    "R52": "Smerte, ikke klassifisert annet sted",
    "Q998": "Annet spesifisert kromosomavvik",
    "H918": "Annet spesifisert hørselstap",
    "Q220": "Atresi i pulmonalklaff",
    "Q210": "Ventrikkelseptumdefekt",
    "D27": "Godartet svulst i eggstokk",
    "R073": "Annen brystsmerte",
    "L089": "Uspesifisert lokal infeksjon i hud eller underhud",
    "F918": "Annen spesifisert atferdsforstyrrelse",
    "F333": "Tilbakevendende depressiv lidelse med aktuell alvorlig episode med psykotisk symptom",
    "H932": "Annen unormal lydoppfatning",
    "F800": "Spesifikk artikulasjonsforstyrrelse",
    "E228": "Annen spesifisert hyperfunksjon av hypofyse",
    "G909": "Uspesifisert forstyrrelse i det autonome nervesystemet",
    "J448": "Annen spesifisert kronisk obstruktiv lungesykdom",
    "G930": "Hjernecyste",
    "Q048": "Annen spesifisert medfødt misdannelse i hjernen",
    "Q040": "Medfødt misdannelse i corpus callosum",
    "F985": "Stamming",
    "F933": "Overdreven, patologisk søskenrivalisering",
    "39": "Unknown",
    "I498": "Annen spesifisert hjertearytmi",
    "R10": "Smerte i buk og bekken",
    "E301": "Tidlig pubertet",
    "R47": "Taleforstyrrelser, ikke klassifisert annet sted",
    "E031": "Medfødt hypotyreose uten struma",
    "F848": "Annen spesifisert gjennomgripende utviklingsforstyrrelse",
    "F603": "Emosjonelt ustabil personlighetsforstyrrelse",
    "G510": "Bells parese",
    "M549": "Uspesifisert ryggsmerte",
    "27": "Unknown",
    "H101": "Allergisk konjunktivitt",
    "J451": "Ikke-allergisk astma",
    "E739": "Uspesifisert laktoseintoleranse",
    "H504": "Annen eller uspesifisert heterotropi",
    "F128": "Annen spesifisert psykisk lidelse eller atferdsforstyrrelse som skyldes bruk av cannabinoid",
    "F348": "Annen spesifisert vedvarende affektiv lidelse",
    "F3300": "Tilbakevendende depressiv lidelse med aktuell mild episode uten somatisk syndrom",
    "E10": "Diabetes mellitus type 1",
    "E73": "Laktoseintoleranse",
    "M41": "Skoliose (scoliosis)",
    "M5309": "Unknown",
    "F931": "Fobisk angstlidelse i barndommen",
    "R410": "Uspesifisert desorientering",
    "L20": "Atopisk dermatitt",
    "Q991": "46,XX ekte hermafroditt",
    "H521": "Nærsynthet",
    "F2300": "Akutt polymorf psykose (non-schizofreniform) uten assosiert akutt påkjenning",
    "K120": "Tilbakevendende munnskåld",
    "G473": "Søvnapné",
    "H729": "Uspesifisert perforasjon i trommehinne",
    "J351": "Hypertrofi av mandel",
    "J352": "Hypertrofi av adenoid vev",
    "H491": "Lammelse av nervus trochlearis [4. hjernenerve]",
    "N44": "Testikkeltorsjon",
    "T508": "Forgiftning med diagnostisk middel",
    "R460": "Meget dårlig personlig hygiene",
    "E831": "Forstyrrelse i jernmetabolismen",
    "F339": "Uspesifisert tilbakevendende depressiv lidelse",
    "D801": "Ikke-familiær hypogammaglobulinemi",
    "G804": "Ataktisk cerebral parese",
    "H522": "Astigmatisme",
    "H523": "Anisometropi eller aniseikoni",
    "K599": "Uspesifisert funksjonell forstyrrelse i tarm",
    "G809": "Uspesifisert cerebral parese",
    "Q031": "Atresi av foramen Magendii eller foramen Luschkae",
    "I456": "Preeksitasjonssyndrom",
    "Q748": "Annen spesifisert medfødt misdannelse i ekstremitet",
    "H55": "Nystagmus eller andre irregulære øyebevegelser",
    "F711": "Moderat psykisk utviklingshemming med betydelig atferdsproblem",
    "Q897": "Flere medfødte misdannelser, ikke klassifisert annet sted",
    "Z039": "Unknown",
    "G406": "Uspesifisert epilepsi med tonisk-kloniske anfall",
    "H908": "Uspesifisert blandet mekanisk og nevrogent hørselstap",
    "Q044": "Septooptisk dysplasi",
    "F633": "Trikotillomani",
    "R48": "Dysleksi og andre forstyrrelser i symbolfunksjoner, ikke klassifisert annet sted",
    "K522": "Allergisk eller diettbetinget gastroenteritt eller kolitt",
    "G448": "Annet spesifisert hodepinesyndrom",
    "L309": "Uspesifisert dermatitt",
    "R010": "Godartet og uskyldig hjertebilyd",
    "T008": "Overflateskader som omfatter andre spesifiserte kombinasjoner av kroppsregioner",
    "Q660": "Klumpfot",
    "H527": "Uspesifisert brytningsforstyrrelse",
    "I730": "Raynauds syndrom",
    "T009": "Flere uspesifiserte overflateskader",
    "I442": "Totalt atrioventrikulært blokk",
    "Z950": "Status med hjertepacemaker eller defibrillator",
    "G479": "Upesifisert søvnforstyrrelse",
    "H501": "Divergent konkomiterende skjeling",
    "F318": "Annen spesifisert bipolar affektiv lidelse",
    "H905": "Uspesifisert nevrogent hørselstap",
    "G43": "Migrene",
    "N911": "Sekundær amenoré",
    "L65": "Annet hårtap uten arrdannelse",
    "L80": "Vitiligo",
    "B279": "Uspesifisert mononukleose",
    "F450": "Somatiseringslidelse",
    "X6n4": "Villet egenskade på skole, høyskole eller i skolegård",
    "M705": "Annen bursitt i kne",
    "S508": "Annen spesifisert overflateskade på underarm",
    "S708": "Annen spesifisert overflateskade på hofte eller lår",
    "E107": "Diabetes mellitus type 1 med flere komplikasjoner",
    "N040": "Nefrotisk syndrom med mindre glomerulær abnormitet",
    "F311": "Bipolar affektiv lidelse med aktuell manisk episode uten psykotisk symptom",
    "Q380": "Medfødt misdannelse i lepper, ikke klassifisert annet sted",
    "F239": "Akutt forbigående uspesifisert psykose",
    "F39": "Uspesifisert affektiv lidelse",
    "10": "Unknown",
    "R00": "Unormale hjerteslag",
    "R01": "Bilyd og andre hjertelyder",
    "12": "Unknown",
    "19": "Unknown",
    "Q878": "Annet spesifisert medfødt misdannelsessyndrom, ikke klassifisert annet sted",
    "F2381": "Annen type akutt forbigående psykose med akutt påkjenning",
    "16": "Unknown",
    "X8n2y": "Kroppskrenkelse eller overfall ved annen ulykke på gate eller vei under ukjent aktivitet",
    "23": "Unknown",
    "F300": "Hypomani",
    "F791": "Uspesifisert psykisk utviklingshemming med betydelig atferdsproblem",
    "F120": "Akutt cannabinoidintoksikasjon",
    "17": "Unknown",
    "E611": "Jernmangel",
    "S707": "Flere overflateskader på hofte eller lår",
    "E874": "Blandet forstyrrelse i syre-base-balanse",
    "X6n8": "Villet egenskade i friluft, på hav, sjø eller vann",
    "E778": "Annen spesifisert forstyrrelse i glykoproteinmetabolismen",
    "Q872": "Medfødt misdannelsessyndrom som hovedsaklig omfatter ekstremiteter",
    "T658": "Toksisk virkning av annet spesifisert stoff",
    "91": "Unknown",
    "P220": "Respiratorisk distressyndrom hos nyfødt",
    "P590": "Gulsott hos nyfødt i forbindelse med for tidlig fødsel",
    "P522": "Intraventrikulær ikke-traumatisk blødning hos foster eller nyfødt av Papile grad 3-4",
    "J210": "Akutt bronkiolitt som skyldes respiratorisk syncytialt virus",
    "K519": "Uspesifisert ulcerøs kolitt",
    "R060": "Dyspné",
    "R05": "Hoste",
    "R13": "Dysfagi",
    "J039": "Uspesifisert akutt tonsillitt",
    "C837": "Burkitt lymfom",
    "K508": "Crohns sykdom med annen spesifisert lokalisasjon",
    "M321": "Systemisk lupus erythematosus med affeksjon av nærmere bestemt organ eller system",
    "G433": "Komplisert migrene",
    "M420": "Juvenil osteokondrose i ryggsøylen",
    "Q909": "Uspesifisert Downs syndrom",
    "G058": "Encefalitt, myelitt eller encefalomyelitt ved annen sykdom klassifisert annet sted",
    "M255": "Leddsmerte",
    "T509": "Forgiftning med annet eller uspesifisert legemiddel eller biologiske substans",
    "S311": "Åpent sår i bukvegg",
    "F1000": "Ukomplisert akutt alkoholintoksikasjon",
    "P2102": "Alvorlig fødselsasfyksi med vedvarende lav Apgar ved 5 minutter",
    "S420": "Brudd i krageben",
    "C835": "Lymfoblastisk (diffust) lymfom",
    "C795": "Metastase i knokkel eller benmarg",
    "G048": "Annen spesifisert encefalitt, myelitt eller encefalomyelitt",
    "J157": "Pneumoni som skyldes Mycoplasma pneumoniae",
    "B009": "Uspesifisert herpesvirusinfeksjon",
    "J938": "Annen spesifisert pneumotoraks",
    "P290": "Hjertesvikt hos nyfødt",
    "G030": "Ikke-pyogen meningitt",
    "J189": "Uspesifisert pneumoni",
    "F621": "Vedvarende personlighetsforandring etter psykisk lidelse",
    "H500": "Konvergent konkomiterende skjeling",
    "Z988": "Annen spesifisert status etter kirurgi",
    "H505": "Heterofori",
    "J303": "Annen allergisk rhinitt",
    "L208": "Annen spesifisert atopisk dermatitt",
    "T781": "Annen reaksjon på matvare ikke klassifisert annet sted",
    "D489": "Svulst med usikkert eller ukjent malignitetspotensial med uspesifisert lokalisasjon",
    "H653": "Kronisk mukoid mellomørebetennelse",
    "H741": "Mellomøresykdom med adhesjoner",
    "H951": "Annen lidelse etter mastoidektomi",
    "S407": "Flere overflateskader på skulder eller overarm",
    "H355": "Arvelig netthinnedystrofi",
    "P219": "Uspesifisert fødselsasfyksi",
    "F3311": "Tilbakevendende depressiv lidelse med aktuell moderat episode med somatisk syndrom",
    "N13": "Obstruktiv urinveissykdom og urinveissykdom med refluks",
    "X6n1": "Villet egenskade ved veitrafikkulykke",
    "L230": "Allergisk kontaktdermatitt som skyldes metall",
    "F131": "Skadelig bruk av sedativum eller hypnotikum",
    "L700": "Acne vulgaris",
    "S068": "Annen spesifisert intrakraniell skade",
    "K649": "Uspesifiserte hemoroider",
    "E230": "Hypopituitarisme",
    "G401": "Lokalisasjonsrelatert symptomatisk epilepsi eller epileptiske syndrom med enkle partielle anfall",
    "H652": "Kronisk serøs mellomørebetennelse",
    "M0800": "Juvenil revmatoid artritt i flere lokalisasjoner",
    "F445": "Dissosiativ krampetilstand",
    "T748": "Annen spesifisert mishandlingssyndrom",
    "G710": "Muskeldystrofi",
    "Q713": "Medfødt mangel på hånd eller finger",
    "B027": "Disseminert herpes zoster",
    "F1225": "Cannabinoidavhengighetssyndrom med vedvarende bruk",
    "F310": "Bipolar affektiv lidelse med aktuell hypoman episode",
    "Q873": "Medfødt misdannelsessyndrom som fører til økt vekst",
    "K270": "Akutt magesår i uspesifisert lokalisasjon med blødning",
    "E282": "Polycystisk ovarialt syndrom",
    "Y4n": "Terapeutisk legemiddel eller biologisk substans i terapeutisk dose som årsak til bivirkning eller annen uønsket virkning",
    "F841": "Atypisk autisme",
    "E119": "Diabetes mellitus type 2 uten komplikasjon",
    "H534": "Synsfeltsdefekter",
    "M773": "Hælbenspore",
    "H541": "Alvorlig svekket syn i begge øyne",
    "J310": "Kronisk rhinitt",
    "F312": "Bipolar affektiv lidelse med aktuell manisk episode med psykotisk symptom",
    "F153": "Abstinenstilstand som skyldes bruk av annen stimulant, inklusive kaffein",
    "M8280": "Osteoporose ved annen sykdom klassifisert annet sted, i flere lokalisasjoner",
    "R041": "Blødning fra svelget",
    "E279": "Uspesifisert forstyrrelse i binyre",
    "K769": "Uspesifisert leversykdom",
    "S099": "Uspesifisert hodeskade",
    "P240": "Aspirasjon av mekonium hos nyfødt",
    "P285": "Respirasjonssvikt hos nyfødt",
    "P369": "Uspesifisert bakteriell sepsis hos nyfødt",
    "P942": "Medfødt hypotoni",
    "P704": "Annen hypoglykemi hos nyfødt",
    "Q655": "Uspesifisert medfødt subluksasjon av hofte",
    "G712": "Medfødt myopati",
    "Q251": "Coarctatio aortae",
    "K210": "Gastroøsofageal reflukssykdom med øsofagitt",
    "Q038": "Annen spesifisert medfødt hydrocephalus",
    "C716": "Ondartet svulst i lillehjerne",
    "P914": "Cerebral depresjon hos nyfødt",
    "F180": "Akutt intoksikasjon med flyktig løsemiddel",
    "Z5110": "Unknown",
    "C819": "Uspesifisert Hodgkins sykdom",
    "F609": "Uspesifisert personlighetsforstyrrelse",
    "O600": "For tidlig spontan start av fødselsarbeid uten fødsel",
    "M411": "Juvenil idiopatisk skoliose",
    "P551": "ABO-isoimmunisering hos foster eller nyfødt",
    "K589": "Unknown",
    "W5nxy": "Slått, truffet, sparket, vridd, bitt, klort eller stukket av person, dyr eller plante på ukjent sted under ukjent aktivitet",
    "S014": "Åpent sår i kinn og kjeveleddområde",
    "Q871": "Medfødt misdannelsessyndrom som hovedsaklig fører til kortvoksthet",
    "R456": "Fysisk voldelighet",
    "E703": "Albinisme",
    "G808": "Annen spesifisert cerebral parese",
    "P101": "Hjerneblødning som skyldes fødselsskade",
    "G600": "Arvelig motorisk eller sensorisk nevropati",
    "F718": "Moderat psykisk utviklingshemming med annet spesifisert atferdsproblem",
    "L409": "Uspesifisert psoriasis",
    "G478": "Annen spesifisert søvnforstyrrelse",
    "H539": "Uspesifisert synsforstyrrelse",
    "B950": "Streptokokk serogruppe A, som årsak til sykdom klassifisert i annet kapittel",
    "F338": "Annen spesifisert tilbakevendende depressiv lidelse",
    "H024": "Ptose av øyelokk",
    "F80": "Spesifikke utviklingsforstyrrelser av tale og språk",
    "H535": "Fargeblindhet",
    "F2009": "Paranoid schizofreni med usikkert forløp eller for kort observasjonstid (<1 år)",
    "G919": "Uspesifisert hydrocephalus",
    "F1026": "Alkoholavhengighetssyndrom med episodisk bruk (dipsomani)",
    "Q359": "Uspesifisert ganespalte",
    "F3810": "Tilbakevendende kortvarig depressiv lidelse",
    "H654": "Annen kronisk ikke-purulent mellomørebetennelse",
    "Q211": "Atrieseptumdefekt",
    "F607": "Avhengig personlighetsforstyrrelse",
    "F1925": "Avhengighetssyndrom som skyldes andre eller flere psykoaktive stoffer med vedvarende bruk",
    "Q253": "Medfødt aortastenose",
    "Q379": "Uspesifisert ganespalte med unilateral leppespalte",
    "P043": "Foster eller nyfødt påvirket av mors bruk av alkohol",
    "I959": "Uspesifisert hypotensjon",
    "F511": "Ikke-organisk hypersomni",
    "J382": "Knute på stemmebånd",
    "Q798": "Annen spesifisert medfødt misdannelse i muskel-skjelettsystem",
    "A085": "Annen spesifisert mage-tarminfeksjon",
    "H533": "Annen forstyrrelse i samsyn",
    "I330": "Akutt eller subakutt infeksiøs endokarditt",
    "K501": "Crohns sykdom i tykktarm",
    "G729": "Uspesifisert myopati",
    "C413": "Ondartet svulst i ribben, brystben eller krageben",
    "S350": "Skade på abdominaldel av aorta",
    "Z940": "Status etter transplantert nyre",
    "R522": "Annen kronisk smerte",
    "L940": "Lokalisert skleroderma",
    "J458": "Blandet astma",
    "M7960": "Smerte i ekstremitet i flere lokalisasjoner",
    "M6099": "Uspesifisert myositt i uspesifisert lokalisasjon",
    "Z713": "Kontakt med helsetjenesten for diettveiledning eller -tilsyn",
    "K20": "Øsofagitt",
    "E344": "Genetisk betinget høyvoksthet",
    "G255": "Annen chorea",
    "Q212": "Atrioventrikulær septumdefekt",
    "M217": "Ervervet ulik lengde på ekstremiteter",
    "Y913": "Alvorlig alkoholpåvirkning",
    "C710": "Ondartet svulst i storhjerne unntatt lapper og ventrikler",
    "C478": "Overlappende ondartet svulst i perifer nerve eller det autonome nervesystem",
    "I158": "Annen spesifisert sekundær hypertensjon",
    "C714": "Ondartet svulst i bakhodelapp",
    "G618": "Annen spesifisert inflammatorisk polynevropati",
    "D66": "Arvelig mangel på koagulasjonsfaktor VIII",
    "M431": "Spondylolistese",
    "Q641": "Ekstrofi av urinblære",
    "G049": "Uspesifisert encefalitt, myelitt eller encefalomyelitt",
    "H531": "Subjektiv synsforstyrrelse",
    "Z035": "Observasjon ved mistanke om annen hjerte-karsykdom",
    "S327": "Flere brudd i lumbalkolumna eller bekken",
    "Q938": "Annen spesifisert delesjon av autosomer",
    "J159": "Uspesifisert bakteriell pneumoni",
    "S222": "Brudd i brystben",
    "S301": "Kontusjon av bukvegg",
    "G379": "Uspesifisert demyeliniserende sykdom i sentralnervesystemet",
    "X4n": "Forgiftning, etsing og annen påvirkning av giftige substanser som følge av ulykke og uhell",
    "D649": "Uspesifisert anemi",
    "D471": "Kronisk myeloproliferativ sykdom",
    "I619": "Uspesifisert hjerneblødning",
    "F453": "Somatoform autonom dysfunksjon",
    "E849": "Uspesifisert cystisk fibrose",
    "C180": "Ondartet svulst i blindtarm (coecum)",
    "K610": "Anal abscess",
    "R529": "Uspesifisert smerte",
    "T741": "Fysisk mishandling",
    "A879": "Uspesifisert virusmeningitt",
    "G936": "Hjerneødem",
    "R101": "Smerte lokalisert til øvre abdomen",
    "S220": "Brudd i torakalvirvel",
    "S320": "Brudd i lumbalvirvel",
    "S224": "Flere brudd i ribben",
    "S270": "Traumatisk pneumotoraks",
    "Z082": "Kontakt med helsetjenesten for etterundersøkelse etter kjemoterapi for ondartet svulst",
    "R258": "Andre eller uspesifiserte unormale ufrivillige bevegelser",
    "C920": "Akutt myelogen leukemi",
    "D469": "Uspesifisert myelodysplastisk syndrom",
    "R040": "Epistaxis",
    "E079": "Uspesifisert forstyrrelse i skjoldbruskkjertelfunksjon",
    "D682": "Arvelig mangel på annen koagulasjonsfaktor",
    "K295": "Uspesifisert kronisk gastritt",
    "B370": "Candidastomatitt",
    "E250": "Medfødt adrenogenital forstyrrelse i tilknytning til enzymmangel",
    "H261": "Traumatisk katarakt",
    "K861": "Annen kronisk pankreatitt",
    "K808": "Annen spesifisert gallesten",
    "M759": "Uspesifisert skulderlidelse",
    "G400": "Lokalisasjonsrelatert idiopatisk epilepsi eller epileptiske syndrom med anfall med fokal start",
    "G369": "Uspesifisert akutt disseminert demyelinisering",
    "M2555": "Smerte i hofteledd eller sakroiliakaledd",
    "E804": "Gilberts syndrom",
    "C793": "Metastase i hjerne eller hjernehinne",
    "I479": "Uspesifisert paroksysmal takykardi",
    "I675": "Moyamoyasykdom",
    "G360": "Neuromyelitis optica",
    "C720": "Ondartet svulst i ryggmarg",
    "A811": "Subakutt skleroserende panencefalitt",
    "M222": "Patellofemoral lidelse",
    "K591": "Funksjonell diaré",
    "M2559": "Leddsmerte i uspesifisert lokalisasjon",
    "Q390": "Atresi av spiserør uten fistel",
    "J370": "Kronisk laryngitt",
    "M0803": "Juvenil revmatoid artritt i håndledd",
    "S062": "Diffus hjerneskade",
    "F0691": "Unknown",
    "K297": "Uspesifisert gastritt",
    "S321": "Brudd i korsben",
    "M2550": "Smerte i ledd i flere lokalisasjoner",
    "M2450": "Kontraktur av ledd i flere lokalisasjoner",
    "I471": "Supraventrikulær takykardi",
    "Q743": "Arthrogryposis multiplex congenita",
    "M5408": "Pannikulitt i sakral- eller sakrococcygealregionen",
    "M891": "Vekststopp i epifyse",
    "Z941": "Status etter transplantert hjerte",
    "C942": "Akutt megakaryoblastleukemi",
    "B209": "Hiv-sykdom med uspesifisert infeksjons- eller parasittsykdom",
    "M8902": "Regionalt smertesyndrom i overarm",
    "Q268": "Annen spesifisert medfødt misdannelse i stor vene",
    "Q200": "Truncus arteriosus communis",
    "Q728": "Annen spesifisert reduksjonsdefekt i underekstremitet",
    "Q750": "Kraniosynostose",
    "M0804": "Juvenil revmatoid artritt i ledd mellom knokler i hånd",
    "Q232": "Medfødt mitralstenose",
    "S626": "Brudd i en annen finger enn tommel",
    "F638": "Annen spesifisert vane- eller impulsforstyrrelse",
    "F1226": "Cannabinoidavhengighetssyndrom med episodisk bruk",
    "F1224": "Cannabinoidavhengighetssyndrom, for tiden bruker (aktiv avhengighet)",
    "B270": "Gammaherpesvirusmononukleose",
    "H904": "Unilateralt nevrogent hørselstap uten nedsatt hørsel på motsatt side",
    "M811": "Osteoporose etter ooforektom",
    "Z000": "Kontakt med helsetjenesten for generell helseundersøkelse",
    "M542": "Smerte i nakke",
    "Q818": "Annen spesifisert epidermolysis bullosa",
    "98": "Unknown",
    "Z00": "Generell undersøkelse og utredning av personer uten symptomer eller registrert diagnose",
    "F192": "Avhengighetssyndrom som skyldes andre eller flere psykoaktive stoffer",
    "B27": "Mononukleose (mononucleosis infectiosa)",
    "Q669": "Uspesifisert medfødt deformitet i fot",
    "J45": "Astma",
    "F514": "Natteskrekk [søvnterror]",
    "F81": "Spesifikke utviklingsforstyrrelser av skoleferdigheter, lærevansker",
    "Q870": "Medfødt misdannelsessyndrom som hovedsaklig påvirker ansiktets utseende",
    "96": "Unknown",
    "H54": "Svekket syn inkludert blindhet på ett eller begge øyne",
    "H542": "Moderat svekket syn i begge øyne",
    "S400": "Kontusjon av skulder eller overarm",
    "S009": "Overflateskade på uspesifisert del av hode",
    "S202": "Kontusjon av brystkasse",
    "Q234": "Hypoplastisk venstre hjerte-syndrom",
    "Z611": "Problem i forbindelse med fjerning fra hjemmet i barnealder",
    "R933": "Unormalt funn ved diagnostisk avbildning av annen del fordøyelsessystemet",
    "Z614": "Problem i forbindelse med påstått seksuelt misbruk av barn utført av person som tilhører barnets primærkontakter",
    "Q213": "Fallots tetrade",
    "O240": "Foruteksisterende diabetes mellitus type 1",
    "B948": "Følgetilstand etter annen spesifisert infeksjonssykdom eller parasittsykdom",
    "Z613": "Problem i forbindelse med hendelser som medfører tap av selvrespekt i barnealder",
    "I420": "Dilatert kardiomyopati",
    "S0690": "Uspesifisert intrakraniell skade uten åpen intrakraniell skade",
    "E713": "Forstyrrelse i metabolismen av fettsyre",
    "F629": "Uspesifisert vedvarende personlighetsforandring",
    "F111": "Skadelig bruk av opiat",
    "Q800": "Ichthyosis vulgaris",
    "Q429": "Medfødt mangel på, atresi av eller stenose av uspesifisert del av tykktarm",
    "Z931": "Status med gastrostomi",
    "Q985": "Karyotype 47,XYY",
    "P051": "Liten i forhold til svangerskapslengde",
    "Q763": "Medfødt skoliose som skyldes medfødt knokkelmisdannelse",
    "M218": "Annen spesifisert ervervet deformitet i ekstremitet",
    "N62": "Hypertrofi av bryst",
    "M4145": "Nevromuskulær skoliose i torakolumbalregionen",
    "F2039": "Udifferensiert schizofreni med usikkert forløp eller for kort observasjonstid (<1 år)",
    "K219": "Gastroøsofageal reflukssykdom uten øsofagitt",
    "F505": "Oppkast forbundet med annen psykisk lidelse",
    "F451": "Udifferensiert somatoform lidelse",
    "J47": "Bronkiektasi",
    "R100": "Akutt abdomen",
    "M0829": "Juvenil artritt med systemisk opprinnelse, i uspesifisert lokalisasjon",
    "O60": "For tidlig start av fødselsarbeid og fødsel",
    "Z808": "Opplysning om ondartet svulst i annet spesifisert organ eller system i familieanamnesen",
    "Q121": "Medfødt linseforskyvning",
    "H543": "Mild eller ingen synssvekkelse i begge øyne",
    "H544": "Blindhet i ett øye",
    "E050": "Tyreotoksikose med diffust struma",
    "R002": "Palpitasjon",
    "F064": "Organisk angstlidelse",
    "P050": "Lett i forhold til svangerskapslengde",
    "Q381": "Ankyloglossi",
    "Z711": "Kontakt for mistanke om sykdom uten at noen diagnose stilles",
    "F4482": "Forbigående dissosiativ lidelse [konversjonslidelse] i barne eller ungdomstid",
    "94": "Unknown",
    "C711": "Ondartet svulst i pannelapp",
    "O990": "Anemi som kompliserer svangerskap, fødsel eller barseltid",
    "Y870": "Følgetilstand etter villet egenskade",
    "P0701": "Ekstremt lav fødselsvekt, < 500g",
    "I620": "Ikke-traumatisk subduralblødning",
    "F1500": "Ukomplisert akutt intoksikasjon med annen stimulant, inklusive kaffein, med akutt intoksikasjon",
    "F558": "Misbruk av annet ikke-avhengighetsskapende stoff",
    "O993": "Psykisk lidelse eller sykdom i nervesystemet, som kompliserer svangerskap, fødsel eller barseltid",
    "Z031": "Observasjon ved mistanke om ondartet svulst",
    "Q724": "Longitudinal reduksjonsdefekt i lårben",
    "C402": "Ondartet svulst i lang knokkel i underekstremitet",
    "M090": "Juvenil artritt ved psoriasis",
    "E149": "Uspesifisert diabetes mellitus uten komplikasjon",
    "Q980": "Klinefelters syndrom med karyotype 47,XXY",
    "Z002": "Kontakt med helsetjenesten for undersøkelse ved periode med vekstspurt i barnealder",
    "M796": "Smerte i ekstremitet",
    "N832": "Annen eller uspesifisert ovarialcyste",
    "R072": "Prekordial smerte",
    "X6n6": "Villet egenskade i fellesboform for pleie og omsorg, på sykehjem eller aldershjem",
    "N399": "Uspesifisert forstyrrelse i urinsystemet",
    "D809": "Uspesifisert immunsvikt med overveiende antistoffmangel",
    "C490": "Ondartet svulst i bindevev eller bløtvev i hode, ansikt eller på hals",
    "M860": "Akutt hematogen osteomyelitt",
    "E139": "Annen spesifisert type diabetes mellitus uten komplikasjon",
    "G800": "Spastisk kvadriplegisk cerebral parese",
    "C927": "Annen myelogen leukemi",
    "P741": "Dehydrering hos nyfødt",
    "S520": "Brudd i proksimal ende av ulna",
    "K858": "Annen spesifisert akutt pankreatitt",
    "C081": "Ondartet svulst i sublingvalspyttkjertel",
    "Q336": "Hypoplasi eller dysplasi i lunge",
    "K513": "Ulcerøs rektosigmoiditt",
    "A310": "Mykobakteriell lungeinfeksjon",
    "G418": "Annen spesifisert status epileptikus",
    "Q221": "Medfødt valvulær pulmonalstenose",
    "Q255": "Atresi av arteria pulmonalis",
    "K567": "Uspesifisert ileus",
    "Q175": "Utstående øre",
    "S699": "Uspesifisert skade i håndledd eller hånd",
    "K754": "Autoimmun hepatitt",
    "L010": "Impetigo",
    "N761": "Subakutt eller kronisk vaginitt",
    "E780": "Ren hyperkolesterolemi",
    "B181": "Kronisk virushepatitt B uten deltavirus",
    "L509": "Uspesifisert urticaria",
    "E880": "Forstyrrelse i plasmaproteinmetabolismen, ikke klassifisert annet sted",
    "D569": "Uspesifisert talassemi",
    "S332": "Dislokasjon av sakroiliakalledd og sakrococcygealledd",
    "S325": "Brudd i os pubis",
    "Q018": "Encefalocele med annen spesifisert lokalisasjon",
    "N029": "Tilbakevendende eller vedvarende hematuri ved uspesifisert glomerulær sykdom",
    "H819": "Uspesifisert forstyrrelse i vestibularisfunksjonen",
    "M232": "Menisklidelse som skyldes gammel ruptur eller skade",
    "O141": "Alvorlig preeklampsi",
    "Q786": "Multippel medfødt eksostose",
    "G250": "Essensiell tremor",
    "G09": "Følgetilstand etter betennelsessykdom i sentralnervesystemet",
    "T0280": "Lukkede brudd som omfatter andre spesifiserte kombinasjoner av kroppsregioner",
    "H920": "Øreverk",
    "N038": "Kronisk nefrittisk syndrom med annen spesifisert morfologisk lesjon",
    "G440": "Clusterhodepinesyndrom",
    "N943": "Premenstruelt tensjonssyndrom (PMS)",
    "J300": "Vasomotorisk rhinitt",
    "F03": "Uspesifisert demens",
    "Q239": "Uspesifisert medfødt misdannelse i aortaklaff eller mitralklaff",
    "Q231": "Medfødt aortainsuffisiens",
    "G438": "Annen spesifisert migrene",
    "Q719": "Uspesifisert reduksjonsdefekt i overekstremitet",
    "T012": "Åpne sår som omfatter flere regioner av en eller begge overekstremiteter",
    "T519": "Toksisk virkning av uspesifisert alkohol",
    "T003": "Overflateskader som omfatter flere regioner av en eller begge underekstremiteter",
    "S599": "Uspesifisert skade i underarm",
    "R12": "Halsbrann",
    "H931": "Tinnitus",
    "R065": "Munnpusting",
    "E059": "Uspesifisert tyreotoksikose",
    "F6030": "Emosjonelt ustabil personlighetsforstyrrelse av impulsiv type",
    "B182": "Kronisk virushepatitt C",
    "L510": "Ikke-bulløst erythema multiforme",
    "S807": "Flere overflateskader på legg",
    "H335": "Annen form for netthinneløsning",
    "Q658": "Annen spesifisert medfødt deformitet i hofte",
    "G934": "Uspesifisert encefalopati",
    "G411": "Absens-status",
    "S8280": "Lukket brudd i annen spesifisert del av legg",
    "S852": "Skade på arteria fibularis",
    "S821": "Brudd i proksimal ende av skinneben",
    "B278": "Annen spesifisert mononukleose",
    "F1905": "Akutt intoksikasjon med andre eller flere psykoaktive stoffer med koma",
    "F1305": "Akutt intoksikasjon med sedativum eller hypnotikum med koma",
    "F1003": "Akutt alkoholintoksikasjon med delirium",
    "P915": "Koma hos nyfødt",
    "C925": "Akutt myelomonocyttleukemi",
    "D391": "Unknown",
    "R560": "Feberkramper",
    "D613": "Idiopatisk aplastisk anemi",
    "E049": "Uspesifisert ikke-toksisk struma",
    "G610": "Guillain-Barrés syndrom",
    "P080": "Uvanlig stort barn",
    "I639": "Uspesifisert hjerneinfarkt",
    "M359": "Uspesifisert systemisk affeksjon av bindevev",
    "C491": "Ondartet svulst i bindevev eller bløtvev i overekstremitet eller skulder",
    "G911": "Obstruktiv hydrocephalus",
    "F780": "Annen psykisk utviklingshemming med ingen eller minimalt atferdsproblem",
    "F504": "Overspising forbundet med annen psykisk lidelse",
    "H530": "Amblyopi på grunn av manglende bruk eller suppresjon",
    "I458": "Annen spesifisert ledningsforstyrrelse",
    "F98": "Andre atferdsforstyrrelser og følelsesmessige forstyrrelser som vanligvis oppstår i barne- og ungdomsalder",
    "E148": "Uspesifisert diabetes mellitus med uspesifisert komplikasjon",
    "Z139": "Kontakt med helsetjenesten for populasjonsbasert screeningundersøkelse uten spesifisert formål",
    "Z658": "Annet spesifisert problem i forbindelse med psykososialt forhold",
    "Z610": "Problem i forbindelse med tap av kjær kontakt i barnealder",
    "Z603": "Problem i forbindelse med kulturelle tilpasningsvansker",
    "F790": "Uspesifisert psykisk utviklingshemming med ingen eller minimalt atferdsproblem",
    "Z634": "Problem i forbindelse med familiemedlem som forsvinner eller dør",
    "Z63.4": "Problem i forbindelse med familiemedlem som forsvinner eller dør",
    "R251": "Uspesifisert tremor",
    "H169": "Uspesifisert keratitt",
    "I859": "Øsofagusvaricer uten blødning",
    "K766": "Portal hypertensjon",
    "Q611": "Autosomal recessiv cystenyre",
    "D690": "Allergisk purpura",
    "Q742": "Annen medfødt misdannelse i underekstremitet eller bekken",
    "P071": "Annen lav fødselsvekt",
    "M4197": "Uspesifisert skoliose i lumbosakralregionen",
    "K30": "Funksjonell dyspepsi",
    "I691": "Følgetilstand etter hjerneblødning",
    "E538": "Mangel på annet spesifisert B-vitamin",
    "M5409": "Pannikulitt som angår nakke- og ryggregionen, i uspesifisert lokalisasjon",
    "Q675": "Medfødt deformitet i ryggsøyle",
    "Q169": "Uspesifisert øremisdannelse som forårsaker nedsatt hørsel",
    "H549": "Uspesifisert svekket syn i begge øyne",
    "H189": "Uspesifisert tilstand i hornhinne",
    "E539": "Uspesifisert B-vitaminmangel",
    "E569": "Uspesifisert vitaminmangel",
    "R72": "Unormalt forhold ved hvite blodceller, ikke klassifisert annet sted",
    "R001": "Uspesifisert bradykardi",
    "R391": "Annet vannlatingsproblem",
    "Z914": "Opplysning om tidligere psykisk traume ikke klassifisert annet sted",
    "M220": "Residiverende dislokasjon av kneskål",
    "S509": "Uspesifisert overflateskade på underarm",
    "J00": "Akutt nasofaryngitt",
    "H598": "Annen spesifisert forandring i øyet eller dets omgivelser etter kirurgiske eller medisinske prosedyrer",
    "T141": "Åpent sår på uspesifisert kroppsregion",
    "H506": "Skjeling av mekanisk årsak",
    "M0846": "Pauciartikulær juvenil artritt i kneledd",
    "I493": "Ventrikulær prematur depolarisasjon",
    "Q039": "Uspesifisert medfødt hydrocephalus",
    "D352": "Godartet svulst i hypofyse",
    "E069": "Uspesifisert tyreoiditt",
    "P042": "Foster eller nyfødt påvirket av mors bruk av tobakk",
    "J939": "Uspesifisert pneumotoraks",
    "G443": "Kronisk posttraumatisk hodepine",
    "O364": "Omsorg for eller behandling av mor ved intrauterint dødsfall",
    "G512": "Melkerssons syndrom",
    "J219": "Uspesifisert akutt bronkiolitt",
    "M210": "Ervervet valgusdeformitet ikke klassifisert annet sted",
    "S723": "Brudd i lårbensskaft",
    "Q613": "Uspesifisert cystenyre",
    "Q999": "Uspesifisert kromosomavvik",
    "D229": "Melanocyttnevus med uspesifisert lokalisasjon",
    "Z349": "Kontroll av normalt svangerskap, uspesifisert om første eller senere svangerskap",
    "R208": "Annen eller uspesifisert forstyrrelse i hudens følsomhet",
    "D691": "Kvalitativ blodplatedefekt",
    "Z640": "Problem i forbindelse med uønsket svangerskap",
    "B002": "Herpetisk gingivostomatitt eller faryngotonsillitt",
    "R092": "Respirasjonsstans",
    "F24": "Indusert psykose (vrangforestillingslidelse)",
    "L501": "Idiopatisk urticaria",
    "C718": "Overlappende ondartet svulst i hjerne",
    "O94": "Følgetilstand etter kompliksjon i svangerskap, fødsel eller barseltid",
    "Q874": "Marfans syndrom",
    "N189": "Uspesifisert kronisk nyresykdom",
    "Q681": "Medfødt deformitet i hånd",
    "F488": "Annen spesifisert nevrotisk lidelse",
    "F0642": "Unknown",
    "P780": "Tarmperforasjon i perinatalperioden",
    "R270": "Uspesifisert ataksi",
    "F1920": "Avhengighetssyndrom som skyldes andre eller flere psykoaktive stoffer, for tiden abstinent",
    "S518": "Åpent sår på annen spesifisert del av underarm",
    "F231": "Akutt polymorf schizofreniform psykose",
    "M248": "Annen spesifisert uorden i ledd, ikke klassifisert annet sted",
    "S411": "Åpent sår på overarm",
    "D729": "Uspesifisert tilstand i hvite blodceller",
    "S370": "Skade på nyre",
    "T887": "Unknown",
    "S619": "Åpent sår på uspesifisert del av håndledd eller hånd",
    "F381": "Annen tilbakevendende affektiv lidelse",
    "D802": "Selektiv mangel på immunglobulin A",
    "E743": "Annen forstyrrelse i intestinal absorpsjon av karbohydrat",
    "Q371": "Spaltet hard gane med unilateral leppespalte",
    "T950": "Følgetilstand etter brannskade, etseskade eller frostskade på hode eller hals",
    "G700": "Myasthenia gravis",
    "F515": "Mareritt",
    "S711": "Åpent sår på lår",
    "P140": "Erbs parese som skyldes fødselsskade",
    "L400": "Psoriasis vulgaris",
    "H503": "Intermitterende heterotropi",
    "Q131": "Fraværende regnbuehinne",
    "J399": "Uspesifisert sykdom i øvre luftveier",
    "J302": "Annen sesongavhengig allergisk rhinitt",
    "H720": "Sentral perforasjon i trommehinne",
    "K622": "Prolaps av analkanal",
    "M089": "Uspesifisert juvenil artritt",
    "C311": "Ondartet svulst i ethmoidalsinus",
    "K623": "Rektalprolaps",
    "O200": "Truende abort",
    "B349": "Uspesifisert virusinfeksjon",
    "Q315": "Medfødt laryngomalasi",
    "Z080": "Kontakt med helsetjenesten for etterundersøkelse etter kirurgisk behandling for ondartet svulst",
    "P293": "Vedvarende føtal sirkulasjon",
    "Q423": "Medfødt mangel på, atresi av eller stenose av endetarmsåpning, uten fistel",
    "Z638": "Annet spesifisert problem i forbindelse med primærkontakt",
    "Z617": "Problem i forbindelse med skremmende opplevelse i barnealder",
    "L281": "Prurigo nodularis",
    "L299": "Uspesifisert kløe",
    "Z512": "Unknown",
    "E550": "Aktiv rakitt",
    "C717": "Ondartet svulst i hjernestamme",
    "I270": "Primær pulmonal hypertensjon",
    "Q205": "Kongenitt korrigert transposisjon",
    "H302": "Bakre syklitt",
    "F316": "Bipolar affektiv lidelse med aktuell blandet episode",
    "F072": "Posttraumatisk hjernesyndrom",
    "Z418": "Kontakt med helsetjenesten for annet spesifisert tiltak med annet formål enn å bedre helsetilstanden",
    "K59": "Andre funksjonelle forstyrrelser i tarm",
    "A37": "Kikhoste",
    "Z633": "Problem i forbindelse med fravær av familiemedlem",
    "D180": "Hemangiom med enhver lokalisasjon",
    "Q224": "Medfødt trikuspidalstenose",
    "P928": "Annet spesifisert problem med næringsinntak hos nyfødt",
    "B348": "Annen virusinfeksjon med uspesifisert lokalisasjon",
    "T812": "Utilsiktet punksjon eller laserasjon under kirurgiske eller medisinske prosedyrer, ikke klassifisert annet sted",
    "Q437": "Persisterende kloakk",
    "M0840": "Pauciartikulær juvenil artritt i flere lokalisasjoner",
    "S829": "Brudd i uspesifisert del av legg",
    "S0271": "Flere åpne brudd som omfatter knokkel i skalle eller ansikt",
    "S0601": "Hjernerystelse med åpen intrakraniell skade",
    "F440": "Dissosiativ amnesi",
    "M8188": "Annen spesifisert osteoporose i annen lokalisasjon",
    "K21": "Gastroøsofageal  reflukssykdom",
    "A039": "Uspesifisert shigellose",
    "Z003": "Kontakt med helsetjenesten for undersøkelse ved vekst eller utvikling i ungdomstid",
    "Q911": "Trisomi 18, mosaikk (mitotisk nondisjunksjon)",
    "H91": "Annet hørselstap",
    "F4530": "Somatoform autonom dysfunksjon i hjerte- eller sirkulasjonssystem",
    "E721": "Forstyrrelse i metabolismen av svovelholdige aminosyre",
    "S730": "Dislokasjon av hofte",
    "Q25": "Medfødte misdannelser i store arterier",
    "Z508": "Kontakt med helsetjenesten for behandling som omfatter bruk av annet spesifisert rehabiliteringstiltak",
    "Z813": "Opplysning om misbruk av annet psykoaktivt stoff i familieanamnesen",
    "K710": "Toksisk leversykdom med kolestase",
    "K904": "Malabsorpsjon som skyldes intoleranse, ikke klassifisert annet sted",
    "Q751": "Kraniofacial dysostose",
    "E66": "Fedme",
    "N30": "Cystitt",
    "Z30": "Prevensjonstiltak",
    "S020": "Brudd på skalletak",
    "M351": "Tilstand med elementer fra forskjellige syndromer",
    "P271": "Bronkopulmonal dysplasi som oppstår i perinatalperioden",
    "R491": "Afoni",
    "Z046": "Kontakt med helsetjenesten for generell psykiatrisk undersøkelse begjært av myndigheter",
    "M130": "Uspesifisert polyartritt",
    "P832": "Føtal hydrops som ikke skyldes hemolytisk sykdom",
    "F0644": "Unknown",
    "E90": "Ernæringsforstyrrelse eller metabolsk forstyrrelse ved sykdom klassifisert annet sted",
    "Q680": "Medfødt deformitet i skrå halsmuskel",
    "O049": "Legal komplett eller uspesifisert abort, uten komplikasjon",
    "F155": "Psykotisk lidelse som skyldes bruk av annen stimulant, inklusive kaffein",
    "F150": "Psykisk lidelse eller atferdsforstyrrelse som skyldes bruk av annen stimulant, inklusive kaffein, med akutt intoksikasjon",
    "L639": "Uspesifisert flekkvis alopesi",
    "N912": "Uspesifisert amenoré",
    "J350": "Kronisk tonsillitt",
    "K299": "Uspesifisert gastroduodenitt",
    "Q140": "Medfødt misdannelse i glasslegeme",
    "I499": "Uspesifisert hjertearytmi",
    "F555": "Misbruk av steroid eller hormon",
    "R012": "Annen hjertelyd",
    "Q640": "Epispadi",
    "M0089": "Artritt eller polyartritt som skyldes annen spesifisert bakteriell mikroorganisme, i uspesifisert lokalisasjon",
    "M0083": "Artritt eller polyartritt som skyldes annen spesifisert bakteriell mikroorganisme, i håndledd",
    "F648": "Unknown",
    "Q935": "Annen delesjon av del av kromosom",
    "Q410": "Medfødt mangel på, atresi av eller stenose av tolvfingertarm",
    "Q204": "Dobbelt innløp til hjertekammer",
    "M8612": "Annen akutt osteomyelitt i overarm",
    "Q792": "Exomphalos eller omphalocele",
    "O030": "Spontan inkomplett abort komplisert med infeksjon i kjønnsorganer eller bekken",
    "P291": "Hjertearytmi hos nyfødt",
    "E871": "Hypoosmolalitet eller hyponatremi",
    "Q433": "Medfødt misdannelse i tarmfeste",
    "I472": "Ventrikkeltakykardi",
    "Q391": "Atresi av spiserør med øsofagotrakeal fistel",
    "Q246": "Medfødt hjerteblokk",
    "P77": "Nekrotiserende enterokolitt hos foster eller nyfødt",
    "Q257": "Annen medfødt misdannelse i arteria pulmonalis",
    "M8605": "Akutt hematogen osteomyelitt i bekkenregion eller lår",
    "Q447": "Annen medfødt misdannelse i lever",
    "K831": "Obstruksjon av gallegang",
    "P75": "Mekoniumileus ved cystisk fibrose",
    "N049": "Nefrotisk syndrom med uspesifisert morfologisk lesjon",
    "T913": "Følgetilstand etter skade på ryggmarg",
    "F530": "Lett psykisk eller atferdsmessig forstyrrelse i barseltiden, ikke klassifisert annet sted",
    "N139": "Uspesifisert obstruktiv urinveierssykdom eller urinveierssykdom med refluks",
    "J860": "Pyotoraks med fistel",
    "93": "Unknown",
    "E030": "Medfødt hypotyreose med diffust struma",
    "A480": "Gassgangren",
    "Q937": "Delesjon med annet komplekst rearrangement",
    "M413": "Torakogen skoliose",
    "H900": "Bilateralt mekanisk hørselstap",
    "L100": "Pemphigus vulgaris",
    "H472": "Synsnerveatrofi",
    "L600": "Inngrodd negl",
    "C812": "(Klassisk) Hodgkin lymfom av blandingstype",
    "H659": "Uspesifisert ikke-purulent mellomørebetennelse",
    "F680": "Forsterking av somatisk symptom av psykisk årsak",
    "G931": "Anoksisk hjerneskade ikke klassifisert annet sted",
    "I319": "Uspesifisert sykdom i perikard",
    "Z087": "Kontakt med helsetjenesten for etterundersøkelse etter kombinasjonsbehandling for ondartet svulst",
    "A410": "Sepsis som skyldes Staphylococcus aureus",
    "D800": "Arvelig hypogammaglobulinemi",
    "N760": "Akutt vaginitt",
    "Z948": "Status etter annet spesifisert transplantert organ eller vev",
    "F1005": "Akutt alkoholintoksikasjon med koma",
    "C495": "Ondartet svulst i bindevev eller bløtvev i bekken",
    "M330": "Juvenil dermatomyositt",
    "N188": "Unknown",
    "N312": "Slapp nevrogen blære ikke klassifisert annet sted",
    "Q642": "Medfødt uretraklaff i bakre del av urinrør",
    "Z5089": "Kontakt med helsetjenesten for enkel rehabilitering",
    "E878": "Annen forstyrrelse i elektrolytt- eller væskebalanse, ikke klassifisert annet sted",
    "Q676": "Pectus excavatum",
    "Q540": "Hypospadi i penishode",
    "K802": "Gallesten uten galleblærebetennelse",
    "N10": "Akutt tubulointerstitiell nefritt og pyelonefritt",
    "M009": "Uspesifisert pyogen artritt",
    "K529": "Uspesifisert ikke-infeksiøs gastroenteritt eller kolitt",
    "I633": "Hjerneinfarkt forårsaket av trombose i hjernearterie",
    "Z090": "Kontakt med helsetjenesten for etterundersøkelse etter kirurgisk behandling for annen tilstand",
    "D819": "Uspesifisert kombinert immunsvikt",
    "K409": "Enkeltsidig eller uspesifisert lyskebrokk uten obstruksjon eller gangren",
    "C921": "Kronisk myelogen leukemi, BCR/ABL-positiv",
    "S2730": "Annen skade i lunge uten åpent sår til brysthule",
    "M814": "Legemiddelutløst osteoporose",
    "Q618": "Annen spesifisert cystenyresykdom",
    "Z700": "Kontakt med helsetjenesten for rådgivning i forbindelse med holdning til seksualitet",
    "T740": "Vanskjøtsel",
    "T910": "Følgetilstand etter overflateskade eller åpent sår på hals eller trunkus",
    "T047": "Knusningsskader som omfatter brystkasse med buk, nedre del av rygg eller bekken med ekstremiteter",
    "M2486": "Annen spesifisert uorden i kneledd, ikke klassifisert annet sted",
    "Z511": "Unknown",
    "C930": "Akutt monoblast/monocyttleukemi",
    "O021": "Missed abortion",
    "T018": "Åpne sår som omfatter andre spesifiserte kombinasjoner av kroppsregioner",
    "A081": "Akutt gastroenteritt som skyldes norovirus",
    "Z018": "Kontakt med helsetjenesten for annen spesifisert undersøkelse hos person uten symptom eller registrert diagnose",
    "M8900": "Regionalt smertesyndrom i flere lokalisasjoner",
    "T142": "Brudd i uspesifisert kroppsregion",
    "C492": "Ondartet svulst i bindevev eller bløtvev i underekstremitet eller hofte",
    "C499": "Ondartet svulst i bindevev eller bløtvev med uspesifisert lokalisasjon",
    "M081": "Juvenil ankyloserende spondylitt",
    "M412": "Annen idiopatisk skoliose",
    "T941": "Følgetilstand etter skade i uspesifisert kroppsregion",
    "Z045": "Undersøkelse eller observasjon etter annen påført skade",
    "S378": "Skade på annet spesifisert bekkenorgan",
    "J630": "Aluminiose i lunge",
    "L40": "Psoriasis",
    "O04": "Legalt svangerskapsavbrudd",
    "F69": "Uspesifisert forstyrrelse av voksen personlighet eller atferd",
    "R62": "Uteblivelse av forventet normal fysiologisk utvikling",
    "Q421": "Medfødt mangel på, atresi av eller stenose av endetarm eller analkanal, uten fistel",
    "T313": "Brannskade som omfatter 30-39% av kroppsoverflate",
    "G939": "Uspesifisert hjernelidelse",
    "N000": "Akutt nefrittisk syndrom med mindre glomerulær abnormitet",
    "K759": "Uspesifisert inflammatorisk leversykdom",
    "C400": "Ondartet svulst i skulderblad eller lang knokkel i overekstremitet",
    "D560": "Alfa-talassemi",
    "Q652": "Uspesifisert medfødt dislokasjon av hofte",
    "S823": "Brudd i distal ende av skinneben",
    "S826": "Brudd i lateral malleol",
    "T846": "Infeksjon eller betennelsesreaksjon som skyldes innvendig fiksasjonsanordning",
    "C780": "Metastase i lunge",
    "C110": "Ondartet svulst på øvre vegg i nasopharynx",
    "M0900": "Juvenil artritt ved psoriasis, i flere lokalisasjoner",
    "K830": "Kolangitt",
    "K758": "Annen spesifisert inflammatorisk leversykdom",
    "Q058": "Sakral spina bifida uten hydrocephalus",
    "E161": "Annen hypoglykemi",
    "M799": "Uspesifisert bløtvevssykdom",
    "J961": "Kronisk respirasjonssvikt",
    "M320": "Legemiddelutløst systemisk lupus erythematosus",
    "Q774": "Akondroplasi",
    "M4120": "Annen idiopatisk skoliose i flere lokalisasjoner i ryggsøylen",
    "Q620": "Medfødt hydronefrose",
    "Q549": "Uspesifisert hypospadi",
    "H471": "Uspesifisert papilleødem",
    "F1300": "Ukomplisert akutt intoksikasjon med sedativum eller hypnotikum",
    "M4125": "Annen idiopatisk skoliose i torakolumbalregionen",
    "I636": "Hjerneinfarkt forårsaket av ikke-pyogen cerebral venøs trombose",
    "C494": "Ondartet svulst i bindevev eller bløtvev i buken",
    "J698": "Pneumoni forårsaket av annet fast stoff eller væske",
    "C709": "Ondartet svulst med uspesifisert lokalisasjon i hjerne- eller ryggmargshinne",
    "M328": "Annen spesifisert form for systemisk lupus erythematosus",
    "E110": "Diabetes mellitus type 2 med koma",
    "H811": "Godartet paroksysmal vertigo",
    "K908": "Annen spesifisert intestinal malabsorpsjon",
    "L511": "Bulløst erythema multiforme",
    "G728": "Annen spesifisert myopati",
    "M319": "Uspesifisert nekrotiserende vaskulitt",
    "D441": "Unknown",
    "M313": "Granulomatose med polyangiitt",
    "Z930": "Status med trakeostomi",
    "J151": "Pneumoni som skyldes Pseudomonas",
    "D333": "Godartet svulst i hjernenerve",
    "N390": "Urinveisinfeksjon med uspesifisert lokalisasjon",
    "Q057": "Lumbal spina bifida uten hydrocephalus",
    "R252": "Krampe eller spasme",
    "H050": "Akutt betennelse i øyehule",
    "H46": "Synsnervebetennelse",
    "R062": "Hvesende respirasjon",
    "S064": "Epiduralblødning",
    "R103": "Smerte lokalisert til annen del av nedre abdomen",
    "T628": "Toksisk virkning av annet spesifisert skadelig stoff spist som mat",
    "S143": "Skade på plexus brachialis",
    "S820": "Brudd i kneskål",
    "M308": "Annen tilstand beslektet med polyarteritis nodosa",
    "F3130": "Bipolar affektiv lidelse med aktuell episode med mild eller moderat depresjon uten somatisk syndrom",
    "H490": "Lammelse av nervus oculomotorius [3. hjernenerve]",
    "G98": "Annen lidelse i nervesystemet, ikke klassifisert annet sted",
    "M0217": "Leddlidelse i ankel eller ledd mellom knokler i fot etter dysenteri",
    "L680": "Hirsutisme",
    "M2309": "Unknown",
    "F481": "Depersonalisasjons- eller derealisasjonssyndrom",
    "T233": "Brannskade av tredje grad på håndledd eller hånd",
    "S0681": "Annen spesifisert intrakraniell skade med åpen intrakraniell skade",
    "Q647": "Annen medfødt misdannelse i urinblære eller urinrør",
    "K602": "Uspesifisert analfissur",
    "M7966": "Smerte i ekstremitet i kne eller legg",
    "C56": "Ondartet svulst i eggstokk",
    "C473": "Ondartet svulst i perifer nerve i toraks",
    "A043": "Infeksjon som skyldes enterohemoragisk Escherichia coli",
    "M088": "Annen spesifisert juvenil artritt",
    "D443": "Unknown",
    "M869": "Uspesifisert osteomyelitt",
    "C474": "Ondartet svulst i perifer nerve i buken",
    "C741": "Ondartet svulst i binyremarg",
    "C313": "Ondartet svulst i sfenoidalsinus",
    "K626": "Sår i endetarmsåpning, analkanal eller endetarm",
    "I425": "Annen restriktiv kardiomyopati",
    "Q159": "Uspesifisert medfødt misdannelse i øye",
    "F1900": "Ukomplisert akutt intoksikasjon med andre eller flere psykoaktive stoffer",
    "F301": "Mani uten psykotisk symptom",
    "L941": "Lineær skleroderma",
    "I64": "Hjerneslag som ikke er spesifisert som blødning eller infarkt",
    "G008": "Annen spesifisert bakteriell meningitt",
    "Z601": "Problem i forbindelse med atypisk foreldresituasjon",
    "D164": "Godartet svulst i knokkel i skalle eller ansikt",
    "R061": "Stridor",
    "Q64": "Andre medfødte misdannelser i urinsystemet",
    "K500": "Crohns sykdom i tynntarm",
    "K739": "Uspesifisert kronisk hepatitt",
    "R960": "Plutselig død",
    "Z857": "Opplysning om ondartet svulst i lymfatisk, bloddannende eller beslektet vev i egen sykehistorie",
    "Z807": "Opplysning om ondartet svulst i lymfatisk, bloddannende eller beslektet vev i familieanamnesen",
    "Q761": "Klippel-Feils syndrom",
    "E848": "Cystisk fibrose med annet spesifisert symptom",
    "M958": "Annen spesifisert ervervet deformitet i muskel-skjelettsystemet",
    "R940": "Unormalt resultat ved funksjonsstudie av sentralnervesystemet",
    "O241": "Foruteksisterende diabetes mellitus type 2",
    "P960": "Medfødt nyresvikt",
    "A499": "Uspesifisert bakterieinfeksjon",
    "P368": "Annen spesifisert bakteriell sepsis hos nyfødt",
    "R011": "Uspesifisert bilyd",
    "F1924": "Avhengighetssyndrom som skyldes andre eller flere psykoaktive stoffer, for tiden bruker (aktiv avhengighet)",
    "F1526": "Avhengighetssyndrom som skyldes bruk av annen stimulant, inklusive kaffein, episodisk bruk",
    "F1025": "Alkoholavhengighetssyndrom med vedvarende bruk",
    "F1520": "Avhengighetssyndrom som skyldes bruk av annen stimulant, inklusive kaffein, for tiden abstinent",
    "H912": "Plutselig idiopatisk hørselstap",
    "F4531": "Somatoform autonom dysfunksjon i øvre tarmkanal",
    "S431": "Dislokasjon av akromioklavikularledd",
    "G258": "Annen spesifisert ekstrapyramidal tilstand eller bevegelsesforstyrrelse",
    "Y609": "Skade som følge av utilsiktet kutt, punksjon, perforasjon eller blødning under uspesifisert medisinsk eller kirurgisk prosedyre",
    "G71": "Primære muskelsykdommer",
    "L930": "Lupus erythematosus discoides",
    "H499": "Uspesifisert paralytisk strabisme",
    "655.5": "Unknown",
    "F986": "Løpsk tale",
    "784.5": "Unknown",
    "L70": "Akne",
    "F604": "Dramatiserende personlighetsforstyrrelse",
    "S200": "Kontusjon av bryst",
    "R908": "Annet spesifisert unormalt funn ved diagnostisk avbildning av sentralnervesystemet",
    "H739": "Uspesifisert lidelse i trommehinne",
    "Z655": "Offer for katastrofe, krig eller annen fiendtlig handling",
    "F067": "Lett organisk kognitiv lidelse",
    "H350": "Bakgrunnsretinopati og karforandringer i netthinne",
    "T200": "Brannskade av uspesifisert grad på hode eller hals",
    "Z135": "Kontakt med helsetjenesten for populasjonsbasert screeningundersøkelse med henblikk på øye- eller øresykdom",
    "N200": "Nyresten",
    "Q244": "Medfødt subaortastenose",
    "M239": "Uspesifisert kneleddlidelse",
    "788.3": "Unknown",
    "788.5": "Unknown",
    "Z015": "Kontakt med helsetjenesten for diagnostisk hud- eller sensitivitetsprøve hos person uten symptom eller registrert diagnose",
    "H40": "Glaukom (glaucoma)",
    "F623": "Unknown",
    "S070": "Knusningsskade i ansikt",
    "787.6": "Unknown",
    "N910": "Primær amenoré",
    "493.9": "Unknown",
    "493.0": "Unknown",
    "345.9": "Unknown",
    "389.9": "Unknown",
    "783.2": "Unknown",
    "359.1": "Unknown",
    "752.7": "Unknown",
    "Z728": "Problem i forbindelse med annet spesifisert problem i forbindelse med levevaner",
    "754.8": "Unknown",
    "691.8": "Unknown",
    "389.1": "Unknown",
    "307.6": "Unknown",
    "H409": "Uspesifisert glaukom",
    "T783": "Angionevrotisk ødem",
    "N922": "Kraftig menstruasjon i pubertet",
    "J30": "Vasomotorisk og allergisk rhinitt",
    "305.9": "Unknown",
    "784.0": "Unknown",
    "R59": "Forstørrede lymfeknuter",
    "A051": "Botulisme",
    "H546": "Moderat svekket syn i ett øye",
    "F2004": "Paranoid schizofreni med inkomplett remisjon",
    "389.7": "Unknown",
    "714.3": "Unknown",
    "333.7": "Unknown",
    "345": "Unknown",
    "070.5": "Unknown",
    "F620": "Vedvarende personlighetsforandring etter katastrofal livshendelse",
    "F349": "Uspesifisert vedvarende affektiv lidelse",
    "F605": "Tvangspreget personlighetsforstyrrelse",
    "747.2": "Unknown",
    "346.9": "Unknown",
    "X78": "Unknown",
    "R480": "Dysleksi eller aleksi",
    "743.3": "Unknown",
    "F600": "Paranoid personlighetsforstyrrelse",
    "781.9": "Unknown",
    "729.1": "Unknown",
    "995.3": "Unknown",
    "345.0": "Unknown",
    "477": "Unknown",
    "693.1": "Unknown",
    "139.0": "Unknown",
    "307.2": "Unknown",
    "306.4": "Unknown",
    "X61": "Unknown",
    "788.4": "Unknown",
    "000.0": "Unknown",
    "564.0": "Unknown",
    "F403": "Unknown",
    "244.9": "Unknown",
    "709.0": "Unknown",
    "250.0": "Unknown",
    "T789": "Uspesifisert skadevirkning",
    "343.0": "Unknown",
    "L200": "Besniers prurigo",
    "K732": "Kronisk aktiv hepatitt, ikke klassifisert annet sted",
    "F079": "Uspesifisert organisk personlighets- eller atferdsforstyrrelse",
    "V71.0": "Unknown",
    "T905": "Følgetilstand etter intrakraniell skade",
    "M258": "Annen spesifisert leddtilstand",
    "K220": "Akalasi av magemunn",
    "345.1": "Unknown",
    "J338": "Annen polypp i bihule",
    "A153": "Lungetuberkulose som er bekreftet på ikke angitt måte",
    "A180": "Tuberkulose i ben eller ledd",
    "F251": "Schizoaffektiv lidelse av depressiv type",
    "X60": "Unknown",
    "315.5": "Unknown",
    "J03": "Akutt tonsillitt (tonsillitis acuta)",
    "F3221": "Unknown",
    "307.7": "Unknown",
    "F195": "Psykotisk lidelse som skyldes bruk av andre eller flere psykoaktive stoffer",
    "H547": "Unknown",
    "342": "Unknown",
    "314.2": "Unknown",
    "Q668": "Annen spesifisert medfødt deformitet i fot",
    "T58": "Toksisk virkning av karbonmonoksid",
    "F202": "Kataton schizofreni",
    "L508": "Annen spesifisert urticaria",
    "F206": "Enkel schizofreni",
    "591": "Unknown",
    "745.4": "Unknown",
    "751.2": "Unknown",
    "343": "Unknown",
    "754.5": "Unknown",
    "Q81": "Epidermolysis bullosa",
    "J984": "Annen lungeforstyrrelse",
    "317.0": "Unknown",
    "F069": "Uspesifisert organisk psykisk lidelse",
    "Q052": "Lumbal spina bifida med hydrocephalus",
    "V65.8": "Unknown",
    "Q833": "Aksessorisk brystvorte",
    "R631": "Polydipsi",
    "Q769": "Uspesifisert medfødt misdannelse i brystkasse",
    "M415": "Annen sekundær skoliose",
    "C410": "Ondartet svulst i knokkel i skalle eller ansikt",
    "C49": "Ondartet svulst i annet bindevev og bløtvev (neoplasma malignum alterius telae conjunctivae et telae mollis)",
    "758.6": "Unknown",
    "Z049": "Unknown",
    "F062": "Organisk paranoid lidelse [schizofrenilignende lidelse]",
    "S451": "Skade på arteria brachialis",
    "S441": "Skade på nervus medianus i overarmsregion",
    "E237": "Uspesifisert forstyrrelse i hypofyse",
    "M091": "Juvenil artritt ved Crohns sykdom",
    "M629": "Uspesifisert muskelsykdom",
    "J840": "Alveolær eller parietoalveolær sykdom",
    "B341": "Enterovirusinfeksjon med uspesifisert lokalisasjon",
    "F552": "Misbruk av analegetikum",
    "F55": "Misbruk av ikke-avhengighetsskapende stoff",
    "Q050": "Cervikal spina bifida med hydrocephalus",
    "I635": "Hjerneinfarkt forårsaket av uspesifisert okklusjon eller stenose i hjernearterie",
    "D591": "Annen autoimmun hemolytisk anemi",
    "Q96": "Turners syndrom",
    "Q868": "Annen spesifisert medfødt misdannelse som skyldes kjent eksogen årsak",
    "F125": "Psykotisk lidelse som skyldes bruk av cannabinoid",
    "F181": "Skadelig bruk av flyktig løsemiddel",
    "692": "Unknown",
    "M08": "Juvenil artritt (arthritis juvenilis)",
    "346.1": "Unknown",
    "B178": "Annen spesifisert akutt virushepatitt",
    "F103": "Alkoholabstinenstilstand",
    "Q809": "Uspesifisert medfødt iktyose",
    "K029": "Uspesifisert karies",
    "Q063": "Annen medfødt misdannelse i cauda equina",
    "278.0": "Unknown",
    "R102": "Smerte i bekken eller perineum",
    "F388": "Annen spesifisert affektiv lidelse",
    "L50": "Urticaria",
    "H532": "Dobbeltsyn",
    "P044": "Foster eller nyfødt påvirket av mors bruk av vanedannende legemiddel",
    "800.3": "Unknown",
    "R074": "Uspesifisert brystsmerte",
    "G36": "Annen akutt disseminert demyelinisering",
    "N921": "Kraftig eller hyppig menstruasjon med uregelmessig syklus",
    "M548": "Annen spesifisert ryggsmerte",
    "720.0": "Unknown",
    "N310": "Detrusorhyperrefleksi ikke klassifisert annet sted",
    "Z629": "Uspesifisert problem i forbindelse med oppfostring",
    "Z991": "Avhengighet av respirator",
    "Q318": "Annen spesifisert medfødt misdannelse i strupehode",
    "446.8": "Unknown",
    "P713": "Tetani hos nyfødt uten kalsium- eller magnesiummangel",
    "942": "Unknown",
    "E232": "Diabetes insipidus",
    "T286": "Etseskade av spiserør",
    "Q400": "Medfødt hypertrofisk pylorusstenose",
    "H525": "Akkommodasjonsforstyrrelse",
    "Z733": "Problem i forbindelse med stress ikke klassifisert annet sted",
    "742.2": "Unknown",
    "493": "Unknown",
    "345.4": "Unknown",
    "A040": "Infeksjon som skyldes enteropatogen Escherichia coli",
    "445.4": "Unknown",
    "Z738": "Annet spesifisert problem med håndtering av tilværelsen",
    "626.0": "Unknown",
    "474.0": "Unknown",
    "Z628": "Annet spesifisert problem i forbindelse med oppfostring",
    "250": "Unknown",
    "749.2": "Unknown",
    "G40.8": "Annen spesifisert epilepsi",
    "W76": "Unknown",
    "R739": "Uspesifisert hyperglykemi",
    "H50": "Annen form for skjeling",
    "367.0": "Unknown",
    "381.1": "Unknown",
    "Z624": "Problem i forbindelse med følelsesmessig forsømmelse av barn",
    "314.0": "Unknown",
    "759.8": "Unknown",
    "E955.2": "Unknown",
    "611.1": "Unknown",
    "E788": "Annen spesifisert forstyrrelse i lipoproteinmetabolismen",
    "F108": "Annen spesifisert psykisk lidelse eller atferdsforstyrrelse som skyldes bruk av alkohol",
    "Z632": "Problem i forbindelse med utilstrekkelig støtte fra familie",
    "704.0": "Unknown",
    "F112": "Opiatavhengighetssyndrom",
    "307.1": "Unknown",
    "R96": "Annen plutselig død av ukjent årsak",
    "Q056": "Torakal spina bifida uten hydrocephalus",
    "G119": "Uspesifisert arvelig ataksi",
    "M139": "Uspesifisert artritt",
    "G91": "Hydrocephalus",
    "490": "Unknown",
    "854": "Unknown",
    "D331": "Godartet svulst med infratentoriell lokalisasjon i hjerne",
    "579.0": "Unknown",
    "783.4": "Unknown",
    "Q043": "Annen reduksjonsdeformitet i hjernen",
    "M54": "Ryggsmerte",
    "I60": "Subaraknoidalblødning",
    "Q53": "Ikke-descendert testikkel",
    "Q730": "Medfødt mangel på uspesifisert ekstremitet",
    "E531": "Pyridoxinmangel",
    "S063": "Fokal hjerneskade",
    "F070": "Organisk personlighetsforstyrrelse",
    "G412": "Kompleks partiell status epileptikus",
    "F984": "Stereotyp bevegelsesforstyrrelse",
    "H650": "Akutt serøs mellomørebetennelse",
    "H52": "Brytningsforstyrrelser  og akkomodasjonsforstyrrelser",
    "D50": "Jernmangelanemi",
    "G44": "Andre hodepinesyndromer",
    "E730": "Medfødt laktasemangel",
    "Z001": "Kontakt med helsetjenesten for rutinemessig helseundersøkelse av barn",
    "J950": "Funksjonsfeil ved trakeostomi",
    "H511": "Konvergensinsuffisiens eller konvergenseksess",
    "M349": "Uspesifisert systemisk sklerose",
    "Z03": "Medisinsk observasjon og vurdering der mistanke om sykdommer og tilstander blir avkreftet",
    "T902": "Følgetilstand etter brudd på knokkel i skalle eller ansikt",
    "K071": "Anomali i forholdet mellom kjever og skallebasis",
    "732.4": "Unknown",
    "G824": "Spastisk tetraplegi",
    "P521": "Intraventrikulær ikke-traumatisk blødning hos foster eller nyfødt av Papile grad 2",
    "F669": "Uspesifisert psykoseksuell forstyrrelse",
    "F309": "Uspesifisert manisk episode",
    "R80": "Isolert proteinuri",
    "T310": "Brannskade som omfatter mindre enn 10% av kroppsoverflate",
    "Z999": "Avhengighet av ikke spesifisert teknisk hjelpemiddel eller innretning",
    "359": "Unknown",
    "Z811": "Opplysning om alkoholmisbruk i familieanamnesen",
    "319": "Unknown",
    "N085": "Glomerulær forstyrrelse ved systemisk bindevevssykdom",
    "P278": "Annen spesifisert kronisk sykdom i lunge eller luftveier, som oppstår i perinatalperioden",
    "B378": "Candidainfeksjon med annen spesifisert lokalisasjon",
    "582.3": "Unknown",
    "277.0": "Unknown",
    "Q541": "Penil hypospadi",
    "M894": "Annen hypertrofisk osteoartropati",
    "H743": "Annen ervervet abnormitet i øreknokler",
    "R521": "Kronisk intraktabel smerte",
    "L401": "Generalisert pustuløs psoriasis",
    "278": "Unknown",
    "710.0": "Unknown",
    "B35": "Hudsoppsykdom",
    "E236": "Annen forstyrrelse i hypofyse",
    "J869": "Pyotoraks uten fistel",
    "Z768": "Kontakt med helsetjenesten under annen spesifisert omstendighet",
    "K603": "Anal fistel",
    "K638": "Annen spesifisert sykdom i tarm",
    "Z510": "Unknown",
    "C967": "Annen spesifisert ondartet svulst utgått fra lymfoid, hematopoetisk eller beslektet vev",
    "S098": "Annen spesifisert hodeskade",
    "Q262": "Fullstendig anomal lungeveneforbindelse",
    "L710": "Perioral dermatitt",
    "D823": "Immunsvikt som følge av arvelig defekt respons på Epstein-Barr-virus",
    "Z014": "Kontakt med helsetjenesten for generell eller rutinemessig gynekologisk undersøkelse hos person uten symptom eller registrert diagnose",
    "N398": "Annen spesifisert forstyrrelse i urinsystemet",
    "M7962": "Smerte i ekstremitet i overarm eller albue",
    "P961": "Abstinenssymptom hos nyfødt som følge av mors bruk av legemidler og andre psykoaktive stoffer",
    "C851": "Uspesifisert B-cellelymfom",
    "Z364": "Prenatal diagnostikk med henblikk på veksthemming hos foster ved hjelp av ultralyd eller annen fysisk undersøkelsesmetode",
    "O301": "Omsorg for eller behandling av mor ved trillingsvangerskap",
    "M7967": "Smerte i ekstremitet i ankel eller fot",
    "Z719": "Kontakt med helsetjenesten for uspesifisert rådgivning eller veiledning",
    "O680": "Fødsel eller forløsning komplisert av unormal hjertefrekvens hos foster",
    "J380": "Parese av stemmebånd eller strupehode",
    "M329": "Uspesifisert systemisk lupus erythematosus",
    "Q392": "Medfødt øsofagotrakeal fistel uten atresi",
    "E111": "Diabetes mellitus type 2 med ketoacidose",
    "P070": "Ekstremt lav fødselsvekt",
    "F1524": "Avhengighetssyndrom som skyldes bruk av annen stimulant, inklusive kaffein, for tiden bruker (aktiv avhengighet)",
    "F1921": "Avhengighetssyndrom som skyldes andre eller flere psykoaktive stoffer, for tiden abstinent, men i beskyttede omgivelser",
    "F229": "Uspesifisert paranoid psykose",
    "Q233": "Medfødt mitralinsuffisiens",
    "F107": "Residual tilstand eller sent innsettende psykotisk lidelse som skyldes bruk av alkohol",
    "F1930": "Ukomplisert abstinenstilstand som skyldes andre eller flere psykoaktive stoffer",
    "K566": "Annen eller uspesifisert tarmobstruksjon",
    "X591y": "Påvirkning fra uspesifisert faktor ved ulykke eller uhell ved veitrafikkulykke under ukjent aktivitet",
    "P249": "Uspesifisert aspirasjonssyndrom hos nyfødt",
    "Q188": "Annen spesifisert medfødt misdannelse i ansikt eller hals",
    "N037": "Kronisk nefrittisk syndrom med diffus halvmåne-glomerulonefritt",
    "H210": "Hyphema",
    "14": "Unknown",
    "L813": "«Café-au-lait»-flekker",
    "P228": "Annet spesifisert respirasjonsbesvær hos nyfødt",
    "R091": "Pleuritt",
    "M303": "Mukokutant lymfeknutesyndrom",
    "Q851": "Tuberøs sklerose",
    "E754": "Nevronal ceroid lipofuscinose",
    "N201": "Sten i urinleder",
    "D589": "Uspesifisert arvelig hemolytisk anemi",
    "Y907": "Påvist alkoholmengde 200-239mg/100ml (2.00-2.39 promille)",
    "P009": "Foster eller nyfødt påvirket av uspesifisert tilstand hos mor",
    "C699": "Ondartet svulst med uspesifisert lokalisasjon i øye",
    "R400": "Somnolens",
    "C857": "Annen spesifisert type non-Hodgkin lymfom",
    "M932": "Osteochondritis dissecans",
    "J36": "Peritonsillær abscess",
    "Z850": "Opplysning om ondartet svulst i fordøyelsesorgan i egen sykehistorie",
    "K720": "Akutt eller subakutt leversvikt",
    "I610": "Subkortikal intracerebral blødning i hjernehalvdel",
    "Y906": "Påvist alkoholmengde 120-199mg/100ml (1.20-1.99 promille)",
    "R636": "Utilstrekkelig inntak av mat eller væske",
    "K523": "Ubestemt kolitt",
    "K291": "Annen akutt gastritt",
    "Q914": "Trisomi 13, meiotisk nondisjunksjon",
    "H163": "Interstitiell eller dyp keratitt",
    "C343": "Ondartet svulst i lungeunderlappens bronkie- eller lungevev",
    "A046": "Enteritt som skyldes Yersinia enterocolitica",
    "E058": "Annen spesifisert tyreotoksikose",
    "P282": "Cyanoseanfall hos nyfødt",
    "R629": "Uspesifisert uteblivelse av forventet normal fysiologisk utvikling",
    "G248": "Annen spesifisert dystoni",
    "Z718": "Kontakt med helsetjenesten for annen spesifisert rådgivning eller veiledning",
    "P90": "Kramper hos nyfødt",
    "L405": "Psoriasis med artropati",
    "D610": "Genetisk betinget aplastisk anemi",
    "S0631": "Fokal hjerneskade med åpen intrakraniell skade",
    "Q968": "Annen spesifisert variant av Turners syndrom",
    "G560": "Karpaltunnelsyndrom",
    "Z501": "Kontakt med helsetjenesten for rehabiltering med annen fysikalsk behandling",
    "O85": "Barselfeber",
    "J206": "Akutt bronkitt som skyldes rinovirus",
    "Q543": "Perineal hypospadi",
    "Z036": "Observasjon ved mistanke om toksisk virkning av inntatt stoff",
    "Q245": "Misdannelse av koronarkar",
    "Q525": "Sammenvokste kjønnslepper",
    "C470": "Ondartet svulst i perifer nerve i hode, ansikt eller hals",
    "M726": "Nekrotiserende fasciitt",
    "F1251": "Psykotisk lidelse med i hovedsak vrangforestilling som skyldes bruk av cannabinoid",
    "M414": "Nevromuskulær skoliose",
    "R31": "Uspesifisert hematuri",
    "R35": "Polyuri",
    "Q165": "Medfødt misdannelse av det indre øret",
    "Q019": "Uspesifisert encefalocele",
    "Q542": "Penoskrotal hypospadi",
    "Q558": "Annen spesifisert medfødt misdannelse i mannlige kjønnsorganer",
    "P399": "Uspesifisert infeksjon i perinatalperioden",
    "E440": "Moderat protein-/energiunderernæring",
    "I421": "Hypertrofisk obstruktiv kardiomyopati",
    "I780": "Arvelig hemoragisk teleangiektasi",
    "K631": "Perforasjon av tarm",
    "I340": "Ikke-revmatisk mitralinsuffisiens",
    "P011": "Foster eller nyfødt påvirket av for tidlig vannavgang",
    "R198": "Annet spesifisert symptom eller tegn med tilknytning til fordøyelsessystemet eller buken",
    "I151": "Hypertensjon sekundær til annen nyresykdom",
    "R262": "Vanskeligheter med å gå, ikke klassifisert annet sted",
    "P082": "Overtidig barn som ikke er tungt i forhold til svangerskapslengde",
    "P809": "Uspesifisert hypotermi hos nyfødt",
    "sample_norwegian": "æ å ø Æ Ø Å",
}
